'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{fileURLToPath,pathToFileURL}=require('node:url');
const ROOT='/workspace/scratch/9a5ec23b7f4b/LightForge',OUT=__dirname,threads=Number(process.argv[2]||4),label=process.argv[3]||'baseline';
const digest=b=>crypto.createHash('sha256').update(b).digest('hex');
const records=[];let run=0,invocation=0;const captures=[]; const captureDir=process.env.LIGHTFORGE_CAPTURE_DIR;
function captureTensor(t,key){const bytes=Buffer.from(t.data.buffer,t.data.byteOffset,t.data.byteLength),name=key+'.bin';fs.writeFileSync(path.join(captureDir,name),bytes);return {type:t.type,dims:t.dims,file:name,bytes:bytes.length,sha256:digest(bytes)};}
function capture(name,feeds,outputs){if(!captureDir||run!==1)return;fs.mkdirSync(captureDir,{recursive:true});const id=String(++invocation).padStart(2,'0')+'-'+name;captures.push({id,name,feeds:Object.fromEntries(Object.entries(feeds).map(([k,t])=>[k,captureTensor(t,id+'-feed-'+k)])),outputs:Object.fromEntries(Object.entries(outputs).map(([k,t])=>[k,captureTensor(t,id+'-output-'+k)]))});fs.writeFileSync(path.join(captureDir,'manifest.json'),JSON.stringify({threads,runtime:'1.20.1',sampleRate:44100,samples:253440,seed:2025,language:0,captures},null,2)+'\n');}
function record(r){records.push(r);console.log(JSON.stringify(r));}
async function main(){
const GAME=require(ROOT+'/web/analysis/game.js');global.location={href:pathToFileURL(ROOT+'/web/analysis/worker.js').href};global.fetch=async input=>new Response(fs.readFileSync(fileURLToPath(new URL(String(input),global.location.href))));
const raw=require(ROOT+'/web/analysis/vendor/ort.wasm.min.js');raw.env.wasm.numThreads=threads;raw.env.wasm.proxy=false;raw.env.wasm.wasmPaths=ROOT+'/web/analysis/vendor/';
const ort={Tensor:raw.Tensor,env:raw.env,InferenceSession:{async create(source,options){const p=fileURLToPath(source),name=path.basename(p).replace('.onnx',''),bytes=fs.readFileSync(p),at=performance.now(),session=await raw.InferenceSession.create(bytes,{...options,...(label==='arena'?{enableCpuMemArena:true,enableMemPattern:true}:{}),...(label==='shape'?{freeDimensionOverrides:{B:1,T:574,...(name==='encoder'?{L:253440}:{}),...(name==='dur2bd'?{N:1}:{})}}:{})});record({kind:'load',name,seconds:(performance.now()-at)/1000,bytes:bytes.length,rss:process.memoryUsage().rss});return{async run(feeds){const at=performance.now(),outputs=await session.run(feeds);record({kind:'infer',name,run,seconds:(performance.now()-at)/1000,feeds:Object.fromEntries(Object.entries(feeds).map(([k,t])=>[k,{dims:t.dims,type:t.type}])),outputs:Object.fromEntries(Object.entries(outputs).map(([k,t])=>[k,{dims:t.dims,type:t.type,sha256:digest(Buffer.from(t.data.buffer,t.data.byteOffset,t.data.byteLength))}])),rss:process.memoryUsage().rss});capture(name,feeds,outputs);return outputs;},async release(){const at=performance.now();await session.release();record({kind:'release',name,seconds:(performance.now()-at)/1000,rss:process.memoryUsage().rss});}};}}};
const b=fs.readFileSync('/workspace/scratch/9a5ec23b7f4b/native-mdx-comparison-2.2.4/demo-20s/wasm-waveform.float32le'),wave=new Float32Array(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)),voice=wave.slice(3840,3840+253440);
const game=await GAME.create({ort,baseUrl:pathToFileURL(ROOT+'/web/analysis/models/game/').href});const notes=[];try{for(run=1;run<=Number(process.argv[4]||2);run++){const at=performance.now();notes.push(await game.infer(voice,0,2025));record({kind:'passage',run,seconds:(performance.now()-at)/1000,notes:notes.at(-1).length});}}finally{await game.release();}
assert.deepEqual(notes[0],notes[1]);
fs.writeFileSync(path.join(OUT,`${label}-${threads}.json`),JSON.stringify({threads,label,samples:voice.length,voiceSha256:digest(Buffer.from(voice.buffer)),runtime:raw.env.versions.web,notes,records,scope:'Local x86 WASM profile on one 5.746-second actual separated voice excerpt, not a phone speed claim'},null,2)+'\n');
}
main().catch(e=>{console.error(e);process.exitCode=1;});
