/* Exercises the production worker with real WAV Range fetches and packaged WASM.
 * Node's ESM loader needs a filesystem WASM glue path; only that URL is remapped.
 */
const fs=require('fs'),path=require('path'),http=require('http'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..'),ort=require(root+'/web/analysis/vendor/ort.wasm.min.js');let rangeCount=0,maxRange=0;
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url));if(!p.startsWith(root)||!fs.existsSync(p)||fs.statSync(p).isDirectory()){res.writeHead(404);res.end();return;}let size=fs.statSync(p).size;let match=/bytes=(\d+)-(\d+)/.exec(req.headers.range||'');let start=0,end=size-1,status=200;if(match){start=Number(match[1]);end=Math.min(end,Number(match[2]));status=206;rangeCount++;maxRange=Math.max(maxRange,end-start+1);}res.writeHead(status,{'Content-Length':end-start+1,'Content-Type':p.endsWith('.wav')?'audio/wav':'application/octet-stream','Content-Range':`bytes ${start}-${end}/${size}`,'Accept-Ranges':'bytes'});fs.createReadStream(p,{start,end}).pipe(res);});
server.listen(0,'127.0.0.1',async()=>{const base=`http://127.0.0.1:${server.address().port}/web/analysis/`;
 const env=ort.env.wasm;Object.defineProperty(env,'wasmPaths',{configurable:true,get:()=>root+'/web/analysis/vendor/',set:()=>{}});
 const context={console,URL,DataView,Float32Array,Float64Array,Uint32Array,Int32Array,ArrayBuffer,performance,ort,location:{href:base+'worker.js'},fetch:(url,opt)=>fetch(new URL(url,base),opt),postMessage:m=>{if(m.type==='progress'&&m.value.progress>.90)console.log(m.value);}};context.self=context;
 context.importScripts=(...args)=>{for(const name of args){if(name.includes('ort.wasm'))continue;vm.runInContext(fs.readFileSync(root+'/web/analysis/'+name,'utf8'),context,{filename:name});}};vm.createContext(context);vm.runInContext(fs.readFileSync(root+'/web/analysis/worker.js','utf8'),context,{filename:'worker.js'});
 async function run(url){return new Promise((resolve,reject)=>{context.postMessage=m=>{if(m.type==='result')resolve(m.value);if(m.type==='error')reject(new Error(m.message));};context.onmessage({data:{audioUrl:url,options:{sensitivity:0.82}}});});}
 try{let started=performance.now();const result=await run(`http://127.0.0.1:${server.address().port}/research/test_audio22050.wav`);assert(result.engine.neural);assert(result.bpm>88&&result.bpm<99);assert(result.beats.length>300);assert(result.beatConfidence>0.7);assert.equal(result.sections[0].start,0);assert.equal(result.sections.at(-1).end,result.duration);assert(result.onsets.length>500);assert(rangeCount>20);assert(maxRange<500000);assert(result.waveform.every(x=>x>=0&&x<=1));assert(result.beats.every((x,i,a)=>x>=0&&x<result.duration&&(i===0||x>a[i-1])));fs.writeFileSync(root+'/research/glass_castle_analysis.json',JSON.stringify(result,null,2));let rejected=false;try{await run(`http://127.0.0.1:${server.address().port}/web/analysis/models/features.json`);}catch(e){rejected=/PCM WAV/.test(e.message);}assert(rejected);let report={productionWorker:'PASS',neuralModel:'BeatNet model1',bpm:result.bpm,beats:result.beats.length,downbeats:result.downbeats.length,meter:result.meter,confidence:result.beatConfidence,onsets:result.onsets.length,sections:result.sections.length,duration:result.duration,rangeRequests:rangeCount,maxAudioReadBytes:maxRange,elapsedSeconds:(performance.now()-started)/1000,invalidAudio:'PASS'};fs.writeFileSync(root+'/research/analysis_verification.json',JSON.stringify(report,null,2));console.log(report);}catch(e){console.error(e);process.exitCode=1;}finally{server.close();}});
