'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const ROOT=path.resolve(__dirname,'..');
function load(root=ROOT,clock={now:()=>0}){const c=vm.createContext({performance:clock,Date,DOMException});c.self=c;for(const name of ['telemetry','dsp','bass-notes'])vm.runInContext(fs.readFileSync(path.join(root,'web/analysis',name+'.js'),'utf8'),c);return c;}
function recorder(){const calls=[],active=[];return {calls,active,measure(name,fn){assert.equal(active.length,0,'Distinct DSP metric scopes must not enclose one another');active.push(name);try{return fn();}finally{assert.equal(active.pop(),name);calls.push(name);}}};}
function rhythmData(){const n=1000,beat=new Float32Array(n),down=new Float32Array(n),rms=new Float32Array(n).fill(.2),fineRms=new Float32Array(n*4).fill(.2),bass=new Float32Array(n),mid=new Float32Array(n),high=new Float32Array(n),colour=new Float32Array(n*3),chroma=new Float32Array(Math.ceil(n/10)*12);for(let i=25;i<n;i+=25){beat[i]=.9;if(i%100===25)down[i]=.9;bass[i]=1;mid[i]=.8;high[i]=.9;fineRms[i*4]=.8;}return {duration:n*.02,beat,down,rms,fineRms,bass,mid,high,colour,chroma,chromaStep:.2};}
function featureConfig(){return {windowLength:32,hop:4,bands:Array.from({length:136},(_,i)=>({start:i%15,weights:[1],frequency:50+i*20}))};}
test('tempo, beat decoding, meter/downbeat selection and structure have distinct serial execution scopes',()=>{const c=load();for(const options of [{decoder:'transformer'},{decoder:'crnn'},{bpmOverride:120}]){const telemetry=recorder(),result=c.LightForgeDSP.summarize(rhythmData(),{...options,telemetry});assert.ok(result.beats.length>5);for(const name of ['tempo_inference','beat_tracking','downbeat_tracking','structural_analysis'])assert.ok(telemetry.calls.includes('performance.'+name),name);assert.equal(telemetry.calls.includes('performance.drum_analysis'),false);assert.equal(telemetry.active.length,0);}});
test('silence omits unexecuted tempo/downbeat work and disabled percussion remains unobserved',()=>{const c=load(),telemetry=recorder();const quiet=new Float32Array(100);c.LightForgeDSP.trackBeats(quiet,quiet,quiet,{telemetry});assert.equal(telemetry.calls.length,0);assert.equal(c.LightForgeDSP.estimatePercussionEvidence({}, {enabled:false,telemetry}),null);assert.equal(telemetry.calls.length,0);c.LightForgeDSP.estimatePercussionEvidence({duration:1},{enabled:true,attacks:[],telemetry});assert.deepEqual(telemetry.calls,['performance.drum_analysis']);});
test('feature spans accumulate all120 executed chunks beyond the raw96-span retention limit',()=>{let tick=0;const c=load(ROOT,{now:()=>tick++}),telemetry=c.LightForgeAnalysisTelemetry.create('rhythm'),extractor=new c.LightForgeDSP.FeatureExtractor(featureConfig(),telemetry),samples=Float32Array.from({length:1500},(_,i)=>Math.sin(i*.2));for(let i=0;i<120;i++)extractor.extract(samples,0,1);const profile=telemetry.snapshot();assert.equal(profile.spans.length,96);assert.equal(profile.spanSummary['performance.feature_generation'].count,120);assert.equal(profile.spanSummary['performance.feature_generation'].totalMs,120);});
test('invalid clock remains null while feature numerical results are unaffected',()=>{let tick=0;const c=load(ROOT,{now:()=>++tick===3?NaN:tick}),telemetry=c.LightForgeAnalysisTelemetry.create('rhythm'),config=featureConfig(),samples=Float32Array.from({length:1500},(_,i)=>Math.sin(i*.2)),timed=new c.LightForgeDSP.FeatureExtractor(config,telemetry).extract(samples,0,2),plain=new c.LightForgeDSP.FeatureExtractor(config).extract(samples,0,2);assert.deepEqual(structuredClone(timed),structuredClone(plain));assert.equal(telemetry.snapshot().spanSummary['performance.feature_generation'].totalMs,null);});
test('bass decimation and feature kernels have separate scopes and do not include reader IO',async()=>{const c=load(),telemetry=recorder(),duration=1.5,pcm=Float32Array.from({length:Math.ceil(duration*22050)},(_,i)=>.3*Math.sin(i*2*Math.PI*55/22050)),reader={duration,async mono22050(start,count){assert.equal(telemetry.active.length,0);const out=new Float32Array(count);for(let i=0;i<count;i++)out[i]=pcm[start+i]||0;return out;}};const result=await c.LightForgeBass.analyze(reader,{}, {telemetry});assert.ok(result.notes.length);assert.ok(telemetry.calls.includes('performance.resample_normalize'));assert.ok(telemetry.calls.includes('performance.feature_generation'));assert.ok(telemetry.calls.filter(x=>x==='performance.feature_generation').length>75);assert.equal(telemetry.calls.some(x=>x.includes('bass_analysis')),false);});
module.exports={load,recorder,rhythmData,featureConfig};

test('empty feature and decimation kernels remain unobserved',()=>{const c=load(),telemetry=recorder();new c.LightForgeDSP.FeatureExtractor(featureConfig(),telemetry).extract(new Float32Array(0),0,0);new c.LightForgeBass.Extractor(telemetry).decimate(new Float32Array(0),0);assert.equal(telemetry.calls.length,0);});
