'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
require('../web/analysis/dsp.js');require('../web/analysis/bass-notes.js');
const RATE=22050;
function fixture(duration){const pcm=new Float32Array(Math.ceil(duration*RATE));return {pcm,duration,async mono22050(start,count){const a=new Float32Array(count);for(let i=0;i<count;i++)a[i]=pcm[start+i]||0;return a;}};}
function note(reader,start,end,frequency,amplitude=.25,harmonics=true){for(let i=Math.ceil(start*RATE);i<Math.min(reader.pcm.length,end*RATE);i++){const t=i/RATE-start,envelope=Math.min(1,t/.008,(end-i/RATE)/.012),phase=2*Math.PI*frequency*t;reader.pcm[i]+=amplitude*envelope*(Math.sin(phase)+(harmonics?.4*Math.sin(phase*2)+.2*Math.sin(phase*3):0));}}
function kick(reader,start){let phase=0;for(let i=Math.ceil(start*RATE);i<Math.min(reader.pcm.length,(start+.35)*RATE);i++){const t=i/RATE-start;phase+=2*Math.PI*(43+130*Math.exp(-t*32))/RATE;reader.pcm[i]+=.7*Math.sin(phase)*Math.exp(-t*16);}}
async function analyze(reader,options={}){return LightForgeBass.analyze(reader,{},options);}
test('off-grid harmonic bass entrances, pitch changes and releases keep their audio clock',async()=>{const r=fixture(7),truth=[[.637,1.447,55],[2.293,3.217,73.416],[3.217,4.127,82.406],[5.331,6.102,41.203]];for(const n of truth)note(r,...n);const result=await analyze(r);assert.equal(result.notes.length,4);result.notes.forEach((n,i)=>{assert.ok(Math.abs(n.start-truth[i][0])<=.04,`start ${i}: ${n.start}`);assert.ok(Math.abs(n.end-truth[i][1])<=.05,`end ${i}: ${n.end}`);assert.ok(Math.abs(12*Math.log2(n.frequency/truth[i][2]))<.12);assert.ok(n.confidence>=.55);});});
test('louder kicks 50–150 ms around bass entrances do not become the note clock',async()=>{for(const distance of [.05,.075,.1,.125,.15]){const r=fixture(7),truth=[[.637,1.447,55],[2.293,3.217,73.416],[3.217,4.127,82.406],[5.331,6.102,41.203]];for(const n of truth){note(r,...n,.16);kick(r,n[0]-distance);kick(r,n[0]+distance);}const result=await analyze(r);assert.equal(result.notes.length,4);result.notes.forEach((n,i)=>{assert.ok(Math.abs(n.start-truth[i][0])<=(distance===.05?.08:.04),`masked start ${i}, distance ${distance}: ${n.start}`);assert.ok(Math.abs(n.end-truth[i][1])<=.05,`masked end ${i}: ${n.end}`);});}});
test('brief sweeping kick transients, broadband noise and silence do not invent bass notes',async()=>{const drums=fixture(5);for(let t=.5;t<5;t+=.5)kick(drums,t);assert.equal((await analyze(drums)).notes.length,0);const noise=fixture(3);let seed=42;for(let i=0;i<noise.pcm.length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;noise.pcm[i]=.25*(seed/4294967296*2-1);}assert.equal((await analyze(noise)).notes.length,0);const quiet=await analyze(fixture(1));assert.equal(quiet.notes.length,0);assert.ok(quiet.envelope.every(x=>x===0));});
test('pure sustained sub-bass remains eligible with estimated-source labels',async()=>{const r=fixture(3);note(r,.517,2.421,36.708,.3,false);const out=await analyze(r);assert.equal(out.notes.length,1);assert.ok(Math.abs(out.notes[0].start-.517)<.04);assert.ok(Math.abs(out.notes[0].end-2.421)<.05);assert.equal(out.source,'mixture-estimate');assert.equal(out.diagnostics.sourceSeparated,false);assert.equal(out.diagnostics.confidenceIsProbability,false);assert.ok(out.envelope.some(x=>x>.5));});
test('different read chunk sizes preserve phase and note boundaries exactly',async()=>{const r=fixture(12);note(r,9.733,10.561,65.406);note(r,10.571,11.351,98);const a=await analyze(r,{chunkFrames:500}),b=await analyze(r,{chunkFrames:137});assert.deepEqual(a,b);});
test('four-hour stationary pitch summaries use bounded columns without argument spreading',()=>{const length=4*3600*50,frames={length,frequency:new Float32Array(length).fill(55),energy:new Float32Array(length).fill(.2),confidence:new Float32Array(length).fill(.9),harmonics:new Float32Array(length).fill(3)},out=LightForgeBass.summarize(frames,14400);assert.equal(out.notes.length,1);assert.equal(out.notes[0].end,14400);assert.equal(out.envelope.length,length);});
test('cancelled analysis rejects without reading audio',async()=>{const reader=fixture(1);reader.mono22050=()=>{throw new Error('should not read');};const controller=new AbortController();controller.abort();await assert.rejects(analyze(reader,{signal:controller.signal}),{name:'AbortError'});});
