'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{performance}=require('node:perf_hooks');
const E=require('../web/engine/show-engine.js'),P=require('../web/engine/movement-planner.js'),V=require('../web/engine/vehicle-profile.js');
const root=path.resolve(__dirname,'..'),checks=[],metrics={};
const digest=a=>crypto.createHash('sha256').update(a).digest('hex');
function test(name,fn){try{fn();checks.push({name,passed:true});process.stdout.write('PASS '+name+'\n');}catch(e){checks.push({name,passed:false,error:e.stack});process.stderr.write('FAIL '+name+'\n'+e.stack+'\n');}}
function fixture(duration=96){const beats=Array.from({length:duration*2},(_,i)=>i*.5);return {duration,bpm:120,meter:4,beats,downbeats:beats.filter((_,i)=>i%4===0),beatConfidence:.95,waveform:Array(duration*10).fill(.85),energy:Array(duration*50).fill(.85),energyStep:.02,sections:[{start:0,end:32,energy:.85},{start:32,end:64,energy:.85},{start:64,end:duration,energy:.85}].filter(x=>x.start<duration),onsets:[],analysisVersion:3,activityRanges:[{start:0,end:duration}]};}
test('legacy waveform bins use full song timescale for movement salience',()=>{const m=fixture(120);m.energy=[];m.energyStep=.02;m.waveform=Array(120).fill(.05);m.waveform.fill(.99,80,94);m.sections=[{start:0,end:120,energy:.5}];m.phrases=[20,80].map(start=>({start,end:start+12,kind:'drop',confidence:.98,energy:.9}));m.impacts=[];const s=E.generate(m,{dance:'expressive'}),target=s.choreography.targets.find(x=>x.outputId==='charge');assert.equal(target.musicTime,80);metrics.legacySelectedChargeTime=target.musicTime;});
test('movement density independently controls physical command count while retaining hard budgets',()=>{const m=fixture(180);m.phrases=[32,80,128].map(start=>({start,end:start+20,kind:'drop',confidence:.98,energy:.95}));const values=[0,.2,.7,1].map(movementDensity=>E.generate(m,{movementDensity}));assert.equal(values[0].movements.length,0);for(let i=1;i<values.length;i++){assert.ok(values[i].movements.length>=values[i-1].movements.length);assert.equal(values[i].validation.valid,true);for(const [ch,n]of Object.entries(values[i].stats.commandCounts)){const spec=Object.values(V.closureSpecifications).find(s=>s.channel===Number(ch));assert.ok(n<=spec.limit);assert.ok(values[i].stats.danceSeconds[ch]<=spec.danceSeconds+.001);}}metrics.densityCommandCounts=values.map(s=>({density:s.settings.movementDensity,commands:s.movements.length}));});
test('bar anchor and meter correction preserve measured beat times and original analysis',()=>{const m=fixture(24),before=JSON.stringify(m),s=E.generate(m,{downbeatAnchor:1.01,meterOverride:3,dance:'off'}),r=s.choreography.rhythm;assert.deepEqual(r.beats,m.beats);assert.equal(r.correction.snappedAnchor,1);assert.deepEqual(r.downbeats,m.beats.filter((_,i)=>(i-2+3)%3===0));assert.equal(r.meter,3);assert.equal(JSON.stringify(m),before);const pulse=E.frameAt(s,1);assert.equal(pulse[16],255);assert.equal(E.frameAt(s,0)[16],0);});
test('half and double tempo preserve local tempo changes without re-running analysis',()=>{const m=fixture(24);m.beats=[.2,.7,1.2,1.7,2.2,2.6,3,3.4,3.8,4.1,4.4,4.7,5];m.downbeats=[.2,2.2,3.8,5];const a=E.generate(m,{tempoScale:2,dance:'off'}).choreography.rhythm,b=E.generate(m,{tempoScale:.5,dance:'off'}).choreography.rhythm;assert.equal(a.bpm,240);assert.equal(b.bpm,60);assert.deepEqual(b.beats,m.beats.filter((_,i)=>i%2===0));for(let i=0;i<m.beats.length-1;i++){assert.equal(a.beats[i*2],m.beats[i]);assert.equal(a.beats[i*2+1],(m.beats[i]+m.beats[i+1])/2);}});
test('confident swing places explicit eighth-note accents on the measured groove',()=>{const m=fixture(24);m.groove={feel:'swing',subdivisionRatio:2/3,confidence:.95};const s=E.generate(m,{style:'pulse',dance:'off',beatDivision:'eighth'}),offbeats=s.lightEvents.filter(e=>e.kind==='offbeat detail');assert.ok(offbeats.length>0);for(const cue of offbeats){const fraction=(cue.start/.5)%1;assert.ok(Math.abs(fraction-2/3)<1e-6);assert.ok(Math.abs(cue.actualStart-cue.start)<=.010001);}assert.equal(s.choreography.rhythm.groove.feel,'swing');});
test('variation materially changes all three styles including quiet cinematic sections',()=>{const result={};for(const style of ['festival','pulse','cinematic'])for(const energy of [.85,.2]){const m=fixture(32);m.sections[0].energy=energy;m.energy.fill(energy);m.waveform.fill(energy);const unique=new Set(Array.from({length:12},(_,seed)=>digest(E.generate(m,{style,seed,dance:'off'}).frames)));assert.ok(unique.size>=4,style+' '+energy+' has only '+unique.size+' distinct arrangements');result[style+'-'+energy]=unique.size;}metrics.distinctVariations=result;});
test('locking a section preserves its exact bytes while neighboring sections regenerate',()=>{const m=fixture(),a=E.generate(m,{seed:11,dance:'off'}),settings={seed:47,dance:'off',sectionOverrides:{1:{seed:a.sections[1].seed}}},b=E.generate(m,settings);assert.deepEqual(b.frames.subarray(32*50*200,64*50*200),a.frames.subarray(32*50*200,64*50*200));assert.notDeepEqual(b.frames.subarray(0,32*50*200),a.frames.subarray(0,32*50*200));assert.equal(b.sections[1].locked,true);assert.equal(b.sections[1].seed,a.sections[1].seed);assert.deepEqual(b.frames,E.generate(m,JSON.parse(JSON.stringify(settings))).frames);});
test('repeated analyzed sections share a local motif and color identity',()=>{const m=fixture();m.sections[0].recurrenceGroup='section-a';m.sections[2].recurrenceGroup='section-a';m.sections[2].repetitionIndex=1;m.sections[2].similarity=.94;const s=E.generate(m,{dance:'off',seed:13});assert.equal(s.sections[0].seed,s.sections[2].seed);assert.equal(s.sections[0].variant,s.sections[2].variant);assert.equal(s.sections[2].similarity,.94);assert.equal(digest(s.frames.subarray(0,30*50*200)),digest(s.frames.subarray(64*50*200,94*50*200)));});
test('streamed FSEQ header plus existing frame buffer exactly equals contiguous export',()=>{const s=E.generate(fixture(),{dance:'off'}),header=E.fseqHeader(s,'rhythm-test.wav'),whole=E.fseq(s,'rhythm-test.wav');assert.equal(new DataView(header.buffer).getUint16(4,true),header.length);assert.deepEqual(Buffer.concat([Buffer.from(header),Buffer.from(s.frames)]),Buffer.from(whole));assert.throws(()=>E.fseqHeader(s,'../bad.wav'));const broken={...s,frames:s.frames.slice()};broken.frames[14]=255;assert.throws(()=>E.fseqHeader(broken),/not fitted/);metrics.headerBytes=header.length;metrics.sequencePayloadBytes=s.frames.length;});
// Independent per-frame reference handles the documented physical aliases and
// ramp slopes. Randomized streams are compared at non-frame and seek boundaries.
function reference(show,time){const d={26:.5,51:1,77:2,178:.5,204:1,230:2},ramp=new Set([3,4,5,6,7,8,9,10,11,12,13,14]),state=new Float64Array(30),step=show.stepMs/1000;const last=Math.min(show.frameCount-1,Math.floor(time/step+1e-9));for(let f=0;f<=last;f++){const dt=f===last?Math.max(0,Math.min(step,time-f*step)):step,p=f*200;for(let c=0;c<30;c++){if([8,9,10,11,17,18,19].includes(c))continue;let v=show.frames[p+c],on=v>127;if([14,15,28].includes(c)){state[c]=0;continue;}if(c===6||c===7)on=on||show.frames[p+c+2]>127||show.frames[p+c+4]>127;else if(c===16)on=on||show.frames[p+17]>127||show.frames[p+18]>127||show.frames[p+19]>127;state[c]=ramp.has(c+1)&&d[v]?Math.max(0,Math.min(1,state[c]+(on?1:-1)*dt/d[v])):Number(on);if(c===6||c===7)state[c+2]=state[c+4]=state[c];if(c===16)state[17]=state[18]=state[19]=state[c];}}return state;}
test('sparse preview matches independent frame integration through random fades and alias interruptions',()=>{let seed=66;const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};const s={frames:new Uint8Array(1000*200),frameCount:1000,stepMs:20,channels:200,settings:{},sections:[]},ramps=[0,26,51,77,178,204,230,255];for(let f=0;f<1000;f++){if(f)s.frames.set(s.frames.subarray((f-1)*200,f*200),f*200);if(f%7===0)for(const c of [2,3,4,5,6,7,8,9,10,11,12,13])s.frames[f*200+c]=ramps[Math.floor(rnd()*ramps.length)];if(f%11===0)for(const c of [0,1,16,17,18,19,20,21,22,23,24,25,26,27,29])s.frames[f*200+c]=rnd()>.5?255:0;}for(let i=0;i<100;i++){const t=rnd()*19.98,expected=reference(s,t),actual=E.stateAt(s,t).lights;for(let c=0;c<30;c++)assert.ok(Math.abs(expected[c]-actual[c])<1e-8,`${t}s channel${c+1}: ${expected[c]} vs ${actual[c]}`);}const clone=structuredClone(s);assert.deepEqual(E.stateAt(clone,9.713).lights,E.stateAt(s,9.713).lights);s.frames.fill(0);E.invalidatePreview(s);assert.ok(E.stateAt(s,10).lights.every(x=>x===0));});
test('prepared preview supports repeated random seeks without rescanning frame payload',()=>{const s=E.generate(fixture(600),{dance:'off'}),times=Array.from({length:2000},(_,i)=>(i*1.7917)%599.9),start=performance.now();for(const t of times)E.stateAt(s,t);metrics.preview2000RandomSeeksMs=performance.now()-start;metrics.previewLampSegments=s.previewIndex.lights.reduce((n,x)=>n+x.times.length,0);assert.ok(s.previewIndex.lights.every(x=>x.times instanceof Float64Array));const copy=structuredClone(s.previewIndex);assert.equal(copy.lights.length,s.previewIndex.lights.length);});
const files=['web/engine/show-engine.js','web/engine/light-planner.js','web/engine/movement-planner.js','web/engine/vehicle-profile.js'],errors=checks.filter(x=>!x.passed).map(x=>x.name+': '+x.error);const receipt={release:E.version,passed:errors.length===0,checkedAt:new Date().toISOString(),checks,errors,metrics,source_hashes:Object.fromEntries(files.map(f=>[f,digest(fs.readFileSync(path.join(root,f)))])),limitations:['Timing tests validate exported command bytes and independently simulated fades, not measured physical Tesla timing.','Host Node seek timings are diagnostic measurements, not Android performance claims.','Repeated section labels are acoustic similarity estimates, not confirmed chorus semantics.']};fs.mkdirSync(path.join(root,'qa/release-'+E.version),{recursive:true});fs.writeFileSync(path.join(root,'qa/release-'+E.version,'composer-verification.json'),JSON.stringify(receipt,null,2)+'\n');if(errors.length)process.exitCode=1;
