'use strict';
/* Independent binary-level timing regressions. Known fixture event times are
 * specified before generation; expected attacks are not copied from lightEvents. */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const E=require('../web/engine/show-engine.js');
const root=path.resolve(__dirname,'..'),qa=path.join(root,'qa/music-1.3.0'),checks=[];
function check(name,fn){test(name,()=>{try{fn();checks.push({name,passed:true});}catch(e){checks.push({name,passed:false,error:e.message});throw e;}});}
const almost=(a,b,tolerance=1e-7)=>assert.ok(Math.abs(a-b)<=tolerance,`${a} vs expected ${b} ±${tolerance}`);
function fixture(duration=40){const beats=Array.from({length:Math.floor(duration*2)},(_,i)=>i*.5);return {duration,bpm:120,meter:4,beatConfidence:1,beats,downbeats:beats.filter((_,i)=>i%4===0),onsets:[],sections:[{start:0,end:duration,energy:.9,label:'Active music'}],waveform:Array(Math.ceil(duration*50)).fill(.9),energy:Array(Math.ceil(duration*50)).fill(.9),energyStep:.02,activityRanges:[{start:0,end:duration}],analysisVersion:2};}
function binary(show){const b=Buffer.from(E.fseq(show)),offset=b.readUInt16LE(4);assert.equal(b.subarray(0,4).toString(),'PSEQ');assert.equal(b.readUInt32LE(10),200);const count=b.readUInt32LE(14),step=b[18]/1000;assert.equal(b.length-offset,count*200);return {data:b.subarray(offset),count,step};}
function attacks(show,ch){const {data,count,step}=binary(show),times=[];for(let i=0;i<count;i++)if(data[i*200+ch-1]===255&&(!i||data[(i-1)*200+ch-1]===0))times.push(i*step);return times;}
function closest(times,t){return Math.min(...times.map(x=>Math.abs(x-t)));}
function dark(show,start,end){const {data,count,step}=binary(show);for(let i=Math.ceil(start/step+1e-8);i<Math.min(count,Math.floor(end/step-1e-8));i++){assert.ok(data.subarray(i*200,i*200+30).every(x=>x===0),`exterior active at${i*step}`);assert.ok(data.subarray(i*200+175,i*200+193).every(x=>x===0),`RGB active at${i*step}`);}}
function closureRuns(show,ch){const {data,count,step}=binary(show),runs=[];let i=0;while(i<count){let j=i+1,v=data[i*200+ch-1];while(j<count&&data[j*200+ch-1]===v)j++;if(v)runs.push({value:v,start:i*step,end:j*step});i=j;}return runs;}
function assertBudget(show){for(const ch of [35,36,37,38,39,40,41,46]){const r=closureRuns(show,ch),limit=ch<37?20:ch===46?3:6;assert.ok(r.filter(x=>[63,127,191].includes(x.value)).length<=limit);assert.ok(r.filter(x=>x.value===127).reduce((s,x)=>s+x.end-x.start,0)<=30.001);if(ch<37)assert.ok(!r.some(x=>x.value===127));if(r.length){assert.equal(r.at(-1).value,ch<37?63:191);const last=r.at(-1);assert.ok(last.start+(ch>=37&&ch<=41?4:2)<show.duration);}}}
check('known eight-second musical rest is dark in exterior and every RGB zone',()=>{for(const stepMs of [15,20]){const m=fixture();m.activityRanges=[{start:0,end:20},{start:28,end:40}];m.waveform.fill(0,1000,1400);m.energy.fill(0,1000,1400);m.beats=m.beats.filter(t=>t<20||t>=28);m.downbeats=m.downbeats.filter(t=>t<20||t>=28);const s=E.generate(m,{dance:'off',stepMs,beatDivision:'eighth'});dark(s,20.1,27.9);assert.ok(attacks(s,1).some(t=>t>=28&&t<29));}});
check('legacy saved analysis without activityRanges still respects waveform silence',()=>{const m=fixture();delete m.activityRanges;m.waveform.fill(0,1000,1400);m.energy.fill(0,1000,1400);m.beats=m.beats.filter(t=>t<20||t>=28);m.downbeats=m.downbeats.filter(t=>t<20||t>=28);dark(E.generate(m,{dance:'off',beatDivision:'eighth'}),21,27);});
check('last genuine beat survives instead of being replaced by unconditional ending fade',()=>{const m=fixture(10),s=E.generate(m,{dance:'off',style:'pulse',stepMs:20});assert.equal(binary(s).data[475*200+2],255);assert.ok(closest(attacks(s,3),9.5)<1e-8);assert.ok(binary(s).data.subarray(-200).every(x=>x===0));});
check('three-quarter bars honor supplied downbeat phase and do not treat pickup as downbeat',()=>{const m=fixture(14);m.meter=3;m.beats=Array.from({length:28},(_,i)=>.207+i*.5).filter(t=>t<14);m.downbeats=m.beats.filter((_,i)=>i%3===1);const s=E.generate(m,{dance:'off',style:'cinematic',beatDivision:'quarter'}),markers=attacks(s,17);assert.equal(markers.length,m.downbeats.length);for(let i=0;i<markers.length;i++)almost(markers[i],m.downbeats[i],.010001);assert.ok(closest(markers,.207)>.1);});
check('three-quarter fallback bars use three beats when explicit downbeats are absent',()=>{const m=fixture(14);m.meter=3;m.beats=Array.from({length:28},(_,i)=>.207+i*.5).filter(t=>t<14);m.downbeats=[];const expected=m.beats.filter((_,i)=>i%3===0),markers=attacks(E.generate(m,{dance:'off',style:'cinematic',beatDivision:'quarter'}),17);assert.equal(markers.length,expected.length);for(let i=0;i<markers.length;i++)almost(markers[i],expected[i],.010001);});
check('changing tempo follows actual local beat intervals instead of average BPM',()=>{const m=fixture(16);m.beats=[.203,.703,1.203,1.703,2.203,2.603,3.003,3.403,3.803,4.103,4.403,4.703,5.003,5.603,6.203,6.803,7.403,8.003,8.603,9.203];m.downbeats=m.beats.filter((_,i)=>i%4===0);for(const stepMs of [15,20]){const markers=attacks(E.generate(m,{dance:'off',style:'pulse',stepMs,beatDivision:'quarter'}),17);assert.equal(markers.length,m.downbeats.length);for(let i=0;i<markers.length;i++)almost(markers[i],m.downbeats[i],stepMs/2000+.000001);}});
check('known non-grid impact attacks and offsets reach FSEQ within half an export frame',()=>{for(const stepMs of [15,20])for(const offsetMs of [-137,0,173]){const m=fixture(36),expected=[6.003,16.013,26.023];m.impacts=expected.map(time=>({time,strength:1,kind:'fixture event'}));const times=attacks(E.generate(m,{dance:'off',style:'pulse',stepMs,offsetMs}),25);for(const t of expected)assert.ok(closest(times,t+offsetMs/1000)<=stepMs/2000+1e-7,`miss at${t}s step${stepMs} offset${offsetMs}`);}});
check('rounding at activity onset retains the accepted binary attack within half a frame',()=>{for(const stepMs of [15,20]){const m=fixture(14);m.activityRanges=[{start:1.007,end:14}];m.beats=Array.from({length:26},(_,i)=>1.007+i*.5);m.downbeats=m.beats.filter((_,i)=>i%4===0);m.impacts=[{time:1.007,strength:1,kind:'known first sample attack'}];const s=E.generate(m,{dance:'off',style:'pulse',stepMs});assert.ok(closest(attacks(s,1),1.007)<=stepMs/2000+1e-7);dark(s,0,.98);}});
check('higher-salience collision preserves the strong known attack without moving it later',()=>{for(const stepMs of [15,20]){const m=fixture(12);m.onsets=[{time:3.903,strength:.92,band:'bass'}];m.impacts=[{time:4.013,strength:1,kind:'strong hit'}];const s=E.generate(m,{dance:'off',style:'pulse',stepMs,sensitivity:1}),a=attacks(s,25);assert.ok(closest(a,4.013)<=stepMs/2000+1e-7);assert.ok(!a.some(t=>t>3.85&&t<3.96),'weak conflicting attack is deliberately suppressed');assert.ok(s.choreography.lighting.suppressedCollisions>0);}});
check('deterministic variation and per-section style edits preserve independent unaffected sections',()=>{const m=fixture(64);m.sections=[{start:0,end:32,energy:.9,label:'First'},{start:32,end:64,energy:.9,label:'Second'}];const a=E.generate(m,{seed:11,dance:'off'}),b=E.generate(m,{seed:11,dance:'off'}),c=E.generate(m,{seed:47,dance:'off'}),d=E.generate(m,{seed:11,dance:'off',sectionOverrides:{1:{style:'cinematic',intensity:.15}}});assert.deepEqual(a.frames,b.frames);assert.notDeepEqual(a.frames,c.frames);assert.deepEqual(a.frames.subarray(0,30*50*200),d.frames.subarray(0,30*50*200));assert.notDeepEqual(a.frames.subarray(34*50*200),d.frames.subarray(34*50*200));});
check('disabled output masks still win over composed beats, impacts and movement tracks',()=>{const m=fixture(90);m.impacts=[{time:30.013,strength:1,kind:'peak'}];const s=E.generate(m,{outputEnabled:{'left-combined':false,'brakes':false,trunk:false}}),{data,count}=binary(s);for(let i=0;i<count;i++)for(const ch of [7,9,11,25,41])assert.equal(data[i*200+ch-1],0);assert.ok(!s.movements.some(e=>e.channels.includes(41)));});
for(const file of ['baseline-demo-music.json','baseline-sample-music.json','current-demo-music.json','current-sample-music.json'])check('actual recorded analysis exports settled, budget-valid choreography: '+file,()=>{const m=JSON.parse(fs.readFileSync(path.join(qa,file))),s=E.generate(m,{dance:'expressive'});assert.ok(s.validation.valid);assertBudget(s);const targets=s.choreography.targets.filter(x=>x.kind==='dance');assert.ok(targets.length>=5,'available dancing closures each have musical targets');const {data,count}=binary(s);assert.ok(data.subarray((count-1)*200).every(x=>x===0));const landmarks=m.beats.concat(m.sections.map(s=>s.start),(m.impacts||[]).map(x=>x.time),(m.phrases||[]).flatMap(x=>[x.start,x.accentTime].filter(Number.isFinite)));for(const t of targets){assert.ok(closest(landmarks,t.musicTime)<=.000001,'target must originate at an independently supplied beat, phrase or impact');if(m.activityRanges)assert.ok(m.activityRanges.some(r=>t.musicTime>=r.start&&t.musicTime<r.end));}if(m.activityRanges)for(const r of m.activityRanges){const next=m.activityRanges[m.activityRanges.indexOf(r)+1];if(next&&next.start-r.end>.3)dark(s,r.end+.05,next.start-.05);}});
test.after(()=>{const source_hashes={};for(const f of ['web/engine/show-engine.js','web/engine/light-planner.js','web/engine/movement-planner.js','web/engine/vehicle-profile.js'])source_hashes[f]=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex');const errors=checks.filter(x=>!x.passed).map(x=>x.name+': '+x.error);fs.writeFileSync(path.join(root,'qa/release-'+E.version,'light-verification.json'),JSON.stringify({release:E.version,passed:errors.length===0,errors,checks,source_hashes,scope:'Independent known-event fixtures and FSEQ byte inspection; no physical vehicle timing measurement.'},null,2)+'\n');});
