'use strict';
/* Real dedicated Chromium workers, including the archived 1.5 implementation. */
const {chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),qa=path.join(root,'qa/release-1.6.0'),historical=path.join(qa,'historical-engine-1.5.0');
const files=['web/engine/client.js','web/engine/worker.js','web/engine/show-engine.js','web/engine/vehicle-profile.js','qa/release-1.5.0/legacy-1.4-project.json'].concat(fs.readdirSync(historical).filter(n=>n.endsWith('.js')).map(n=>'qa/release-1.6.0/historical-engine-1.5.0/'+n));
const hashes=()=>Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')]));
(async()=>{const source_hashes=hashes(),checks=[],metrics={},errors=[];let browser;
 const server=http.createServer((req,res)=>{const request=decodeURIComponent(req.url.split('?')[0]);if(request==='/'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Migration QA</title>');return;}const base=request.startsWith('/legacy/')?historical:path.join(root,'web'),relative=request.startsWith('/legacy/')?request.slice(8):request.slice(1),target=path.resolve(base,relative);if(!target.startsWith(base+'/')){res.writeHead(403).end();return;}try{res.setHeader('Content-Type','text/javascript');res.end(fs.readFileSync(target));}catch{res.writeHead(404).end();}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 try{browser=await chromium.launch({executablePath:path.resolve(root,'../toolchain/chrome/chrome-headless-shell-linux64/chrome-headless-shell'),args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port);
  await page.evaluate(()=>{window.runWorker=(url,payload)=>new Promise((resolve,reject)=>{const w=new Worker(url);w.onmessage=({data})=>{if(data.type==='progress')return;w.terminate();data.type==='error'?reject(Error(data.message)):resolve(data.value);};w.onerror=e=>{w.terminate();reject(Error(e.message));};w.postMessage(payload);});window.sha=async bytes=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');window.saved=[];});
  const fixture=JSON.parse(fs.readFileSync(path.join(root,'qa/release-1.5.0/legacy-1.4-project.json')));
  metrics.versions=await page.evaluate(async fixture=>{
   const music={duration:24,bpm:120,meter:4,beats:Array.from({length:48},(_,i)=>i*.5),downbeats:Array.from({length:12},(_,i)=>i*2),beatConfidence:.95,waveform:Array(240).fill(.75),sections:[{start:0,end:24,energy:.75}],onsets:[],analysisVersion:4},settings={stepMs:20,dance:'off',vocalFocus:.72,bassFocus:.93,seed:711};
   const generated15=await runWorker('/legacy/worker.js',{action:'generate',music,settings});saved.push({name:'1.5 custom focus',compiled:generated15.compiled,music,settings:{...settings,vocalRegions:[]},defaults:['vocalRegions']});
   const upgraded14Settings={...fixture.settings,vocalFocus:.85,bassFocus:.9};
   const migrated15=await runWorker('/legacy/worker.js',{action:'restore',compiled:fixture.compiled,music:fixture.music,settings:upgraded14Settings});saved.push({name:'1.4 previously rebound by1.5',compiled:migrated15.compiled,music:fixture.music,settings:{...upgraded14Settings,vocalRegions:[]},defaults:['vocalRegions']});
   saved.push({name:'1.4 direct skip upgrade',compiled:fixture.compiled,music:fixture.music,settings:{...upgraded14Settings,vocalRegions:[]},defaults:['vocalRegions','vocalFocus','bassFocus']});
   const result=[];for(const f of saved){const oldFrameHash=f.compiled.sha256,oldFrameData=f.compiled.frameData,oldMetaHash=f.compiled.metaSHA256,r=await runWorker('/engine/worker.js',{action:'restore',compiled:f.compiled,music:f.music,settings:f.settings});
    const firstMigration=JSON.stringify(r.compiled.settingsMigration),again=await runWorker('/engine/worker.js',{action:'restore',compiled:r.compiled,music:f.music,settings:f.settings});result.push({name:f.name,engine:r.show.version,valid:r.show.validation.valid,framesPreserved:await sha(r.show.frames)===oldFrameHash&&await sha(again.show.frames)===oldFrameHash,compressedPreserved:r.compiled.frameData===oldFrameData,metadataPreserved:r.compiled.metaSHA256===oldMetaHash,migration:r.compiled.settingsMigration,expectedDefaults:f.defaults,reopenTraceStable:JSON.stringify(again.compiled.settingsMigration)===firstMigration,rebound:r.compiled.inputDigest!==f.compiled.inputDigest,inputMatchesReopen:r.compiled.inputDigest===again.compiled.inputDigest,guides:r.show.settings.vocalRegions,focus:[r.show.settings.vocalFocus,r.show.settings.bassFocus]});}
   return result;
  },fixture);
  for(const row of metrics.versions){assert.ok(row.valid&&row.framesPreserved&&row.compressedPreserved&&row.metadataPreserved&&row.reopenTraceStable&&row.rebound&&row.inputMatchesReopen);assert.deepEqual(row.guides,[]);assert.deepEqual(row.migration.addedDefaults,row.expectedDefaults);assert.equal(row.migration.to,'1.6.0');assert.equal(row.migration.framesPreserved,true);}assert.deepEqual(metrics.versions[0].focus,[.72,.93]);assert.equal(metrics.versions[1].migration.previous.to,'1.5.0');checks.push({name:'Actual1.5 output,1.4 previously migrated by actual1.5 worker, and direct1.4 upgrade preserve exact frames and reopen with stable migration trace',passed:true});
  metrics.rejectedEdits=await page.evaluate(async()=>{const results=[];for(const f of saved)for(const [name,patch]of Object.entries({nonemptyGuides:{vocalRegions:[{start:3,end:4,kind:'voice'}]},invalidGuideObject:{vocalRegions:{}},invalidGuideNull:{vocalRegions:null},changedIntensity:{intensity:.12},changedVoice:{vocalFocus:.2},changedBass:{bassFocus:.2}})){try{await runWorker('/engine/worker.js',{action:'restore',compiled:f.compiled,music:f.music,settings:{...f.settings,...patch}});results.push({fixture:f.name,name,rejected:false});}catch(e){results.push({fixture:f.name,name,rejected:/match its music and edits/.test(e.message)});}}return results;});assert.ok(metrics.rejectedEdits.every(r=>r.rejected));checks.push({name:'All18 changed settings and nonempty or malformed guide migrations are rejected',passed:true});
  metrics.integrity=await page.evaluate(async()=>{const results=[];for(const [name,mutate]of Object.entries({metadata:c=>c.meta.vehicle='Changed',payloadHash:c=>c.sha256='0'.repeat(64),gzip:c=>c.frameData='bad gzip',shortExpanded:c=>c.frameCount--,longExpanded:c=>c.frameCount++})){const f=saved[0],compiled=structuredClone(f.compiled);mutate(compiled);try{await runWorker('/engine/worker.js',{action:'restore',compiled,music:f.music,settings:f.settings});results.push({name,rejected:false});}catch(e){results.push({name,rejected:true,message:e.message});}}return results;});assert.ok(metrics.integrity.every(r=>r.rejected));checks.push({name:'Eligible default-only migrations still reject metadata, payload hash, gzip and expansion corruption',passed:true});
  metrics.current=await page.evaluate(async()=>{const f=saved[0],settings={...f.settings,vocalRegions:[{start:3,end:4,kind:'instrumental'}]},generated=await runWorker('/engine/worker.js',{action:'generate',music:f.music,settings}),before=JSON.stringify(generated.compiled),restored=await runWorker('/engine/worker.js',{action:'restore',compiled:generated.compiled,music:f.music,settings});return {unchanged:before===JSON.stringify(restored.compiled),hash:await sha(restored.show.frames),expected:generated.compiled.sha256,migration:restored.compiled.settingsMigration||null,guides:restored.show.settings.vocalRegions};});assert.ok(metrics.current.unchanged);assert.equal(metrics.current.hash,metrics.current.expected);assert.equal(metrics.current.migration,null);assert.equal(metrics.current.guides.length,1);checks.push({name:'Exact-current input checksum with nonempty guides bypasses migration and preserves the complete compiled object',passed:true});
  assert.deepEqual(hashes(),source_hashes,'Source changed during migration test');
 }catch(e){errors.push(e.stack);console.error(e.stack);}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
 const receipt={release:'1.6.0',passed:errors.length===0,checkedAt:new Date().toISOString(),checks,metrics,errors,source_hashes,limitations:['Desktop Chromium dedicated workers, WebCrypto and browser gzip were executed. No Android lifecycle or physical Tesla was used.','Migration preserves exported channel payload exactly; the current FSEQ writer may update its producer-version metadata.']};fs.writeFileSync(path.join(qa,'migration-verification.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({passed:receipt.passed,checks:checks.length,scenarios:metrics.versions?.length,rejectedEdits:metrics.rejectedEdits?.length,errors},null,2));if(errors.length)process.exitCode=1;
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
