'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const E=require('../web/engine/show-engine.js'),V=require('../web/engine/vehicle-profile.js');
const root=path.resolve(__dirname,'..'),checks=[],metrics={};
function test(name,fn){try{fn();checks.push({name,passed:true});console.log('PASS '+name);}catch(error){checks.push({name,passed:false,error:error.stack});console.error('FAIL '+name+'\n'+error.stack);}}
function fixture(duration=64){const beats=Array.from({length:duration*2},(_,i)=>i*.5);return {duration,bpm:120,meter:4,beats,downbeats:beats.filter((_,i)=>i%4===0),beatConfidence:.95,waveform:Array(duration*10).fill(.8),energy:Array(duration*50).fill(.8),energyStep:.02,sections:[{start:0,end:duration,energy:.8}],onsets:beats.slice(0,-1).flatMap(t=>[{time:t+.247,strength:.82,band:'high'},{time:t+.133,strength:.79,band:'mid'}]),analysisVersion:5,activityRanges:[{start:0,end:duration}]};}
function detail(m=fixture()){
  m.vocals={available:true,presence:'detected',method:'declared separated-source fixture',source:'separated-vocals',sourceSeparated:true,confidence:.94,envelopeStep:.02,envelope:Array(m.duration*50).fill(0),pitchContour:{step:.04,midi:Array(m.duration*25).fill(0),confidence:Array(m.duration*25).fill(0)},phrases:[{start:6.013,end:16.147,confidence:.94,strength:.83,kind:'singing'},{start:26.031,end:38.143,confidence:.96,strength:.90,kind:'singing'}],accents:[],notes:[]};
  for(const p of m.vocals.phrases){for(let t=p.start+.333,i=0;t<p.end-.3;t+=.571,i++)m.vocals.accents.push({time:t,confidence:.92,strength:.65+(i%3)*.12,source:'separated-vocals',kind:'syllabic-accent'});for(let t=p.start+.10,i=0;t<p.end-.5;t+=1.2,i++)m.vocals.notes.push({start:t,end:Math.min(p.end,t+.95),midi:55+i%5*2,frequency:200,confidence:.89,strength:.82,peakTime:t+.2});for(let i=Math.ceil(p.start*50);i<p.end*50;i++)m.vocals.envelope[i]=.18+.77*Math.pow(.5+.5*Math.sin(i*.41),2);for(let i=Math.ceil(p.start*25);i<p.end*25;i++){m.vocals.pitchContour.midi[i]=56+6*Math.sin(i*.07);m.vocals.pitchContour.confidence[i]=.9;}}
  m.bassNotes=Array.from({length:50},(_,i)=>({start:2.033+i*.9,end:2.633+i*.9,midi:36+i%4*3,frequency:65,confidence:.91,strength:.83}));m.bassAnalysis={confidence:.91,source:'accompaniment-estimate',envelopeStep:.02,envelope:Array(m.duration*50).fill(.65),phrases:[]};return m;
}
const track=(s,ch)=>Array.from({length:s.frameCount},(_,f)=>s.frames[f*200+ch-1]);
const near=(xs,t)=>Math.min(...xs.map(x=>Math.abs(x-t)));
function physicalChecks(s){assert.equal(s.validation.valid,true);assert.ok(s.frames.subarray((s.frameCount-1)*200).every(x=>x===0));for(const [ch,count]of Object.entries(s.stats.commandCounts)){const spec=Object.values(V.closureSpecifications).find(x=>x.channel===Number(ch));assert.ok(count<=spec.limit);assert.ok(s.stats.danceSeconds[ch]<=spec.danceSeconds+.001);}assert.deepEqual(Buffer.from(E.fseq(s)).subarray(E.fseqHeader(s).length),Buffer.from(s.frames));}
test('separated articulations keep the original off-grid source clock through both frame modes and signed offsets',()=>{const m=detail(),sources=m.vocals.phrases.map(p=>p.start).concat(m.vocals.accents.map(a=>a.time),m.vocals.notes.map(n=>n.start));for(const stepMs of [15,20])for(const offsetMs of [-137,173]){const s=E.generate(m,{dance:'off',stepMs,offsetMs}),cues=s.lightEvents.filter(c=>c.role==='vocals');assert.ok(cues.filter(c=>c.articulation).length>=20);for(const c of cues){assert.ok(near(sources,c.sourceEventTime)<1e-8);assert.ok(Math.abs(c.actualStart-(c.sourceEventTime+offsetMs/1000))<=stepMs/2000+1e-7);assert.ok(c.end-c.start<=1.800001);assert.equal(c.sourceSeparated,true);}physicalChecks(s);metrics.articulationCues=cues.filter(c=>c.articulation).length;}});
test('lead singing has articulation contrast and keeps bass, percussion and accompaniment active',()=>{const m=detail(),s=E.generate(m,{dance:'off',beatDivision:'eighth'}),roles=s.choreography.lighting.roles;assert.ok(roles.vocals.accentCues>=20);assert.ok(roles.bass.acceptedEvents>=40);assert.ok(roles.percussion.acceptedCues>0);assert.ok(roles.arrangement.acceptedCues>0);let paired=0,active=0,alternating=0;for(const p of m.vocals.phrases)for(let t=p.start;t<p.end;t+=.04){const lights=E.stateAt(s,t).lights;active++;if(lights[4]>.5&&lights[5]>.5)paired++;if((lights[4]>.5)!==(lights[5]>.5))alternating++;}assert.ok(paired/active<.45);assert.ok(alternating/active>.1);metrics.signatureComposition={pairedBrightFraction:paired/active,alternatingFraction:alternating/active};metrics.roleCoverage=roles;});
test('stable sung pitch and isolated envelope shape real RGB bytes while the exact exterior rhythm stays fixed',()=>{const m=detail(),flat=structuredClone(m);flat.vocals.pitchContour.midi.fill(58);flat.vocals.notes.forEach(n=>n.midi=58);const a=E.generate(m,{dance:'off'}),b=E.generate(flat,{dance:'off'});assert.notDeepEqual(track(a,185),track(b,185));assert.notDeepEqual(track(a,188),track(b,188));assert.deepEqual(a.choreography.rhythm,b.choreography.rhythm);assert.ok(a.choreography.vocalDetail.notes.length);assert.equal(a.choreography.vocalDetail.lyricsAligned,false);});
test('instrumental corrections remove measured voice evidence locally and never mutate original analysis',()=>{const m=detail(),before=JSON.stringify(m),guide={start:8.037,end:13.113,kind:'instrumental'},s=E.generate(m,{dance:'off',vocalRegions:[guide]}),effective=s.choreography.vocalDetail;for(const p of effective.phrases.concat(effective.notes))assert.ok(p.end<=guide.start||p.start>=guide.end);for(const a of effective.accents)assert.ok(a.time<guide.start||a.time>=guide.end);assert.ok(s.lightEvents.filter(c=>c.role==='vocals').every(c=>c.end<=guide.start+.011||c.start>=guide.end-.011));assert.equal(JSON.stringify(m),before);const cleared=E.generate(m,{dance:'off',vocalRegions:[]}),plain=E.generate(m,{dance:'off'});assert.deepEqual(cleared.frames,plain.frames);});
test('explicit voice guides add a labeled phrase without inventing measured notes or syllables',()=>{const m=fixture();m.vocals={available:false,presence:'not_detected',phrases:[],notes:[],accents:[]};const s=E.generate(m,{dance:'off',vocalRegions:[{start:5.137,end:8.213,kind:'voice'}]}),v=s.choreography.vocalDetail;assert.equal(v.phrases.length,1);assert.equal(v.phrases[0].manual,true);assert.equal(v.notes.length,0);assert.equal(v.accents.length,0);assert.equal(v.sourceSeparated,false);assert.ok(s.stats.vocalCues>0);assert.throws(()=>E.generate(m,{vocalRegions:[{start:2,end:4,kind:'voice'},{start:3,end:5,kind:'instrumental'}]}),/overlap/);assert.throws(()=>E.generate(m,{vocalRegions:[{start:2,end:3,kind:'bass'}]}),/voice guide/);});
test('short articulated phrases and cadences never nominate multi-second motor Dance outside their region',()=>{const m=detail(fixture(120));m.vocals.phrases=Array.from({length:18},(_,i)=>({start:8.031+i*5,end:9.181+i*5,confidence:.99,strength:.99,kind:'singing'}));m.vocals.notes=[];m.vocals.accents=[];m.bassNotes=[];const s=E.generate(m,{movementDensity:1});assert.ok(s.choreography.targets.every(t=>t.role!=='vocals'||t.kind==='mirror-arrival'));assert.ok(s.movements.some(e=>e.command==='Dance'));physicalChecks(s);});
test('long sustained vocal and bass phrases compete for expressive gestures with full mechanical lead and return',()=>{const m=detail(fixture(180));m.vocals.phrases=[{start:32.043,end:46.343,confidence:.97,strength:.96,kind:'singing'},{start:110.029,end:126.629,confidence:.97,strength:.96,kind:'singing'}];m.vocals.notes=[];m.vocals.accents=[];m.bassAnalysis.phrases=[{start:66.037,end:83.737,confidence:.97,strength:.98}];const s=E.generate(m,{movementDensity:1}),targets=s.choreography.targets;assert.ok(targets.some(t=>t.role==='vocals'&&t.kind==='dance'));assert.ok(targets.some(t=>t.role==='bass'));for(const e of s.movements.filter(e=>e.intent.type==='prepare'))assert.ok(e.end-e.start>=e.intent.travelSeconds+.29);physicalChecks(s);metrics.movementRoles=targets.reduce((a,t)=>(a[t.role]=(a[t.role]||0)+1,a),{});});
test('saved and corrected detail is deterministic, masks apply and manual lights keep ownership',()=>{const m=detail(),settings={seed:11,dance:'off',vocalRegions:[{start:9,end:10,kind:'instrumental'}],outputEnabled:{'right-signature':false},manualCues:[{id:'manual-signature',outputId:'left-signature',start:7,end:7.4,value:255}]},a=E.generate(m,settings),b=E.generate(JSON.parse(JSON.stringify(m)),JSON.parse(JSON.stringify(settings)));assert.deepEqual(a.frames,b.frames);assert.ok(track(a,6).every(x=>x===0));for(let f=350;f<370;f++)assert.equal(a.frames[f*200+4],255);physicalChecks(a);});
const files=['web/engine/show-engine.js','web/engine/light-planner.js','web/engine/movement-planner.js','web/engine/vehicle-profile.js'],errors=checks.filter(x=>!x.passed).map(x=>x.name+': '+x.error),receipt={release:'1.6.0',passed:!errors.length,checkedAt:new Date().toISOString(),checks,errors,metrics,source_hashes:Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')])),limitations:['Declared-source fixtures validate choreography, corrections, exact export timing and physical command constraints; audio-estimation accuracy is evaluated separately against real reference stems.','Pitch/articulation remain acoustic estimates, not a lyric transcript or word alignment.','Motor timing and preview dynamics are vehicle estimates, not measured physical Tesla response.']};fs.mkdirSync(path.join(root,'qa/release-1.6.0'),{recursive:true});fs.writeFileSync(path.join(root,'qa/release-1.6.0/role-composer-verification.json'),JSON.stringify(receipt,null,2)+'\n');if(errors.length)process.exitCode=1;
