'use strict';
/* Role-aware composition fixtures use declared acoustic event times and inspect
 * exported bytes. They do not establish source-detection or vehicle accuracy. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const E=require('../web/engine/show-engine.js'),V=require('../web/engine/vehicle-profile.js');
const root=path.resolve(__dirname,'..'),checks=[],metrics={};
function test(name,fn){try{fn();checks.push({name,passed:true});console.log('PASS '+name);}catch(e){checks.push({name,passed:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);}}
function fixture(duration=96){const beats=Array.from({length:duration*2},(_,i)=>i*.5);return {duration,bpm:120,meter:4,beats,downbeats:beats.filter((_,i)=>i%4===0),beatConfidence:.95,waveform:Array(duration*10).fill(.85),energy:Array(duration*50).fill(.85),energyStep:.02,sections:[{start:0,end:duration,energy:.85}],onsets:beats.filter((_,i)=>i%2).flatMap(t=>[{time:t+.25,band:'high',strength:.95},{time:t+.12,band:'mid',strength:.91}]).filter(x=>x.time<duration),analysisVersion:4,activityRanges:[{start:0,end:duration}]};}
function roles(m){m.vocals={available:true,presence:'detected',method:'declared test fixture',confidence:.95,envelopeStep:.02,envelope:Array(Math.ceil(m.duration*50)).fill(.75),phrases:[{start:6.013,end:10.347,confidence:.92,strength:.87},{start:24.031,end:31.143,confidence:.94,strength:.91},{start:48.021,end:60.049,confidence:.94,strength:.95}]};m.bassNotes=[{start:3.013,end:3.813,midi:40,frequency:82.407,confidence:.95,strength:.84},{start:6.173,end:6.773,midi:43,frequency:97.999,confidence:.9,strength:.8},{start:8.023,end:9.023,midi:45,frequency:110,confidence:.9,strength:.9},{start:20.027,end:21.627,midi:40,frequency:82.407,confidence:.95,strength:.97},{start:40.041,end:41.641,midi:40,frequency:82.407,confidence:.95,strength:.97}];m.bassAnalysis={method:'declared test fixture',source:'mixture-estimate',confidence:.93,envelope:Array(Math.ceil(m.duration*50)).fill(.8),envelopeStep:.02,phrases:[{start:20.027,end:30.03,accentTime:20.027,confidence:.95,strength:.97},{start:40.041,end:51.04,accentTime:40.041,confidence:.95,strength:.97}]};return m;}
function bytes(show){const file=Buffer.from(E.fseq(show)),offset=file.readUInt16LE(4);assert.equal(file.subarray(0,4).toString(),'PSEQ');assert.equal(file.readUInt32LE(10),200);return file.subarray(offset);}
function track(show,ch){const b=bytes(show);return Buffer.from(Array.from({length:show.frameCount},(_,i)=>b[i*200+ch-1]));}
function onsetTimes(show,ch){const a=track(show,ch),out=[];for(let i=0;i<a.length;i++)if(a[i]===255&&(!i||a[i-1]!==255))out.push(i*show.stepMs/1000);return out;}
const close=(a,b,tol)=>assert.ok(Math.abs(a-b)<=tol,`${a} vs ${b} ±${tol}`);
function nearest(a,t){return Math.min(...a.map(x=>Math.abs(x-t)));}
function budget(show){assert.equal(show.validation.valid,true);for(const [ch,count]of Object.entries(show.stats.commandCounts)){const spec=Object.values(V.closureSpecifications).find(x=>x.channel===Number(ch));assert.ok(count<=spec.limit);assert.ok(show.stats.danceSeconds[ch]<=spec.danceSeconds+.001);}for(const ch of [35,36])assert.ok(!track(show,ch).includes(127));assert.ok(bytes(show).subarray(-200).every(x=>x===0));}

test('singing and pitched bass entrances retain source time plus exactly one user offset',()=>{for(const stepMs of [15,20])for(const offsetMs of [-137,0,173]){const m=roles(fixture()),s=E.generate(m,{stepMs,offsetMs,dance:'off'});for(const p of m.vocals.phrases)assert.ok(nearest(onsetTimes(s,5),p.start+offsetMs/1000)<=stepMs/2000+1e-7);for(let i=0;i<m.bassNotes.length;i++){const n=m.bassNotes[i];assert.ok(nearest(onsetTimes(s,i%2?2:1),n.start+offsetMs/1000)<=stepMs/2000+1e-7);}assert.equal(s.stats.vocalPhraseCount,3);assert.equal(s.stats.bassNoteCount,5);assert.equal(s.stats.vocalCues,3);assert.equal(s.stats.bassNoteCues,5);budget(s);}});
test('held singing phrases use actual legal release codes with an independently expected fade slope',()=>{const m=roles(fixture()),s=E.generate(m,{dance:'off'}),b=bytes(s),p=m.vocals.phrases[0],release=Math.round((p.end-.5)/.02)*.02,off=Math.round(p.end/.02)*.02;assert.equal(b[Math.round((p.start+.2)/.02)*200+4],255);assert.equal(b[Math.round(release/.02)*200+4],26);close(E.stateAt(s,release+.25).lights[4],.5,1e-6);assert.equal(b[Math.round(off/.02)*200+4],0);});
test('separated lane allocation retains every percussion, melody and arrangement byte outside the focused lanes',()=>{const m=roles(fixture()),focused=E.generate(m,{dance:'off',beatDivision:'eighth'}),plain=E.generate(m,{dance:'off',beatDivision:'eighth',vocalFocus:0,bassFocus:0});for(const ch of [3,4,7,8,9,10,11,12,13,14,17,18,19,20,21,22,23,24,26,27,28,30])assert.deepEqual(track(focused,ch),track(plain,ch),'unreserved channel '+ch);assert.ok(focused.choreography.lighting.roles.percussion.acceptedCues>0);assert.ok(focused.choreography.lighting.roles.arrangement.acceptedCues>0);assert.notDeepEqual(track(focused,5),track(plain,5));assert.notDeepEqual(track(focused,1),track(plain,1));metrics.roleCoverage=focused.choreography.lighting.roles;});
test('focus switches change emphasis independently without changing analysis or beat times',()=>{const m=roles(fixture()),before=JSON.stringify(m),a=E.generate(m,{dance:'off',vocalFocus:0,bassFocus:1}),b=E.generate(m,{dance:'off',vocalFocus:1,bassFocus:0}),c=E.generate(m,{dance:'off',vocalFocus:.3,bassFocus:.3});assert.equal(a.stats.vocalCues,0);assert.ok(a.stats.bassNoteCues>0);assert.ok(b.stats.vocalCues>0);assert.equal(b.stats.bassNoteCues,0);assert.notDeepEqual(a.frames,b.frames);assert.ok(c.lightEvents.filter(x=>x.role==='vocals').every(x=>x.end-x.start<=.271));assert.equal(JSON.stringify(m),before);assert.deepEqual(a.choreography.rhythm.beats,m.beats);assert.deepEqual(b.choreography.rhythm.beats,m.beats);});
test('legacy instrumental and generic spectral attacks never become fabricated vocal or pitched-bass events',()=>{const m=fixture();m.onsets.push({time:3.013,strength:1,band:'bass'},{time:6.013,strength:1,band:'mid'});const a=E.generate(m,{dance:'off'}),b=E.generate(m,{dance:'off',vocalFocus:0,bassFocus:0});assert.equal(a.stats.vocalCues,0);assert.equal(a.stats.bassNoteCues,0);assert.deepEqual(a.frames,b.frames);assert.ok(a.lightEvents.every(x=>!x.role));});
test('uncertain role evidence and unavailable singing detection fall back to the intact full arrangement',()=>{const plain=fixture(),m=roles(fixture());m.vocals.phrases.forEach(x=>x.confidence=.2);m.bassNotes.forEach(x=>x.confidence=.2);m.bassAnalysis.phrases.forEach(x=>x.confidence=.2);assert.deepEqual(E.generate(m,{dance:'off'}).frames,E.generate(plain,{dance:'off'}).frames);m.vocals.phrases.forEach(x=>x.confidence=.99);m.vocals.available=false;assert.equal(E.generate(m,{dance:'off'}).stats.vocalCues,0);m.vocals.available=true;m.vocals.presence='not_detected';assert.equal(E.generate(m,{dance:'off'}).stats.vocalCues,0);});
test('long sung regions use sparse confidence-gated contours without creating a syllable clock',()=>{const m=roles(fixture());m.vocals.phrases=[{start:4.013,end:24.013,confidence:.95,strength:.9}];m.vocals.accents=Array.from({length:180},(_,i)=>({time:4.17+i*.1,confidence:.9,strength:.9,estimated:true}));m.vocals.accents.push({time:30.1,confidence:1,strength:1,estimated:true});const s=E.generate(m,{dance:'off'}),c=s.lightEvents.filter(x=>x.estimatedAccent&&x.id==='left-signature');assert.ok(c.length>=6);assert.ok(c.length<=16);for(let i=0;i<c.length;i++){assert.ok(c[i].sourceEventTime>5.113&&c[i].sourceEventTime<23.263);assert.ok(m.vocals.accents.some(x=>x.time===c[i].sourceEventTime));assert.ok(nearest(onsetTimes(s,5),c[i].sourceEventTime)<=.010001);if(i)assert.ok(c[i].sourceEventTime-c[i-1].sourceEventTime>=1.3-1e-7);}assert.equal(s.stats.vocalCues,1);metrics.sparseVocalContourCount=c.length;});
test('vocal and bass phrase movement targets preserve non-grid timing while respecting travel, recovery and budgets',()=>{const m=roles(fixture(180));m.vocals.phrases=[{start:32.043,end:43.843,confidence:.98,strength:.98},{start:80.031,end:93.331,confidence:.98,strength:.98},{start:132.023,end:145.923,confidence:.98,strength:.98}];m.bassNotes=[{start:52.029,end:53.829,midi:40,frequency:82.4,confidence:.95,strength:.95},{start:112.049,end:113.649,midi:43,frequency:98,confidence:.95,strength:.95}];m.bassAnalysis.phrases=[{start:52.029,end:66.329,confidence:.95,strength:.98},{start:112.049,end:126.749,confidence:.95,strength:.98}];for(const stepMs of [15,20])for(const offsetMs of [-137,173]){const s=E.generate(m,{stepMs,offsetMs}),targets=s.choreography.targets.filter(x=>x.role!=='arrangement');assert.ok(targets.some(x=>x.role==='vocals'));assert.ok(targets.some(x=>x.role==='bass'));const sources=m.vocals.phrases.flatMap(x=>[x.start,x.end]).concat(m.bassNotes.map(x=>x.start),m.bassAnalysis.phrases.map(x=>x.start));for(const t of targets){assert.ok(nearest(sources,t.musicTime)<1e-8);close(t.time,t.musicTime+offsetMs/1000,stepMs/2000+1e-7);}for(const move of s.movements.filter(x=>x.intent.type==='prepare'))assert.ok(move.end-move.start>=(move.intent.travelSeconds||0)+.29);budget(s);metrics.movementRoleTargets=targets.reduce((a,x)=>(a[x.role]=(a[x.role]||0)+1,a),{});}});
test('high note density never creates rapid motor commands or breaks output masks and manual ownership',()=>{const m=roles(fixture(96));m.bassNotes=Array.from({length:360},(_,i)=>({start:4.013+i*.25,end:4.213+i*.25,midi:40+i%5,frequency:82.4,confidence:.9,strength:.9}));m.bassAnalysis.phrases=[];m.vocals.phrases=[{start:4.013,end:92.113,confidence:.95,strength:.9}];const s=E.generate(m,{movementDensity:1,outputEnabled:{'left-signature':false,'left-outer':false},manualCues:[{id:'manual-mirror',outputId:'mirrorL',start:10,end:12.5,value:191,label:'Manual fold'},{id:'manual-mirror-home',outputId:'mirrorL',start:15,end:17.5,value:63,label:'Manual unfold'}]});budget(s);assert.ok(track(s,1).every(x=>x===0));assert.ok(track(s,5).every(x=>x===0));assert.equal(s.movements.filter(x=>x.channels.includes(35)).length,2);assert.ok(s.movements.filter(x=>x.command==='Dance').every(x=>x.end-x.start>=4.4-.021));metrics.denseBassAccepted=s.stats.bassNoteCues;});
test('role-aware composition remains deterministic and all lights obey actual silent regions',()=>{const m=roles(fixture()),settings={seed:718,vocalFocus:.88,bassFocus:.92,dance:'off'},a=E.generate(m,settings),b=E.generate(JSON.parse(JSON.stringify(m)),JSON.parse(JSON.stringify(settings)));assert.deepEqual(a.frames,b.frames);m.activityRanges=[{start:0,end:5},{start:12,end:96}];m.energy.fill(0,250,600);m.waveform.fill(0,50,120);const c=E.generate(m,settings),data=bytes(c);for(let f=251;f<599;f++){assert.ok(data.subarray(f*200,f*200+30).every(x=>x===0));assert.ok(data.subarray(f*200+175,f*200+193).every(x=>x===0));}});
const files=['web/engine/show-engine.js','web/engine/light-planner.js','web/engine/movement-planner.js','web/engine/vehicle-profile.js'],errors=checks.filter(x=>!x.passed).map(x=>x.name+': '+x.error),receipt={release:'1.5.0',passed:!errors.length,checkedAt:new Date().toISOString(),checks,errors,metrics,source_hashes:Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')])),limitations:['Fixtures validate scheduling and exported commands for declared event times; source-classification and bass-estimation accuracy need separate audio evaluation.','Singing contours are sparse mixture estimates within classified singing, not lyrics or isolated vocal-note transcription.','Actuator travel and Dance trajectories are vehicle estimates, not measurements from a connected car.']};fs.mkdirSync(path.join(root,'qa/release-1.5.0'),{recursive:true});fs.writeFileSync(path.join(root,'qa/release-1.5.0/role-composer-verification.json'),JSON.stringify(receipt,null,2)+'\n');if(errors.length)process.exitCode=1;
