'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Timeline=require('../web/analysis/semantic-timeline.js');

function fixture(){return {duration:8,beatConfidence:.9,beats:[0,.5,1,1.5,2,2.5,3,3.5],downbeats:[0,2],beatDetails:[{time:0,confidence:.9,barPosition:1,localBpm:120},{time:.5,confidence:.9,barPosition:2,localBpm:120},{time:1,confidence:.9,barPosition:3,localBpm:120},{time:1.5,confidence:.9,barPosition:4,localBpm:120},{time:2,confidence:.9,barPosition:1,localBpm:120}],sections:[{start:0,end:4,energy:.4,label:'verse'},{start:4,end:8,energy:1,label:'chorus'}],phrases:[{start:0,end:2,energy:.5,kind:'phrase'},{start:2,end:4,energy:.9,kind:'phrase'}],onsets:[{time:2,band:'bass',strength:.9}],impacts:[{time:2,strength:1,kind:'drop'}],vocals:{sourceSeparated:true,phrases:[{start:1.98,end:2.8,confidence:.9,strength:.9,kind:'singing'}],notes:[{start:2,end:2.5,confidence:.9,strength:.8,midi:60}],accents:[{time:2,confidence:.9,strength:1,kind:'syllabic-accent'}]},bassNotes:[{start:1.99,end:2.4,confidence:.9,strength:.9,midi:40,frequency:82.4}],bassAnalysis:{sourceSeparated:true,phrases:[{start:1.99,end:2.4,confidence:.8,strength:.8}]}};}
test('timeline preserves source-clock events and exposes cross-stem salience',()=>{const out=Timeline.build(fixture());assert.equal(Timeline.validate(out).valid,true);const accent=out.events.find(x=>x.type==='vocal_accent');assert.equal(accent.rhythm.barPosition,1);assert.ok(accent.relationships.crossStemAgreement>0);assert.ok(out.events.some(x=>x.type==='bass_note'));assert.equal(out.summary.hasSeparatedVocals,true);});
test('timeline reports accompaniment context without falsely claiming an isolated bass stem',()=>{const music=fixture();music.bassAnalysis={source:'separated-accompaniment',sourceSeparated:true,phrases:[{start:1.99,end:2.4,confidence:.8,strength:.8}]};const out=Timeline.build(music),event=out.events.find(x=>x.type==='bass_note');assert.equal(out.schemaVersion,2);assert.equal(out.summary.hasSeparatedBass,false);assert.equal(out.summary.hasSeparatedAccompaniment,true);assert.equal(event.sourceSeparated,false);assert.equal(event.instrumentSeparated,false);assert.equal(event.inputStem,'accompaniment');assert.equal(event.inputStemSeparated,true);});
test('timeline accepts a bass-isolated source only with explicit instrument provenance',()=>{const music=fixture();music.bassAnalysis={source:'isolated-bass-stem',inputStem:'bass',inputStemSeparated:true,instrumentSeparated:true,phrases:[{start:1.99,end:2.4,confidence:.8,strength:.8,instrumentSeparated:true}]};music.bassNotes[0].instrumentSeparated=true;const out=Timeline.build(music),event=out.events.find(x=>x.type==='bass_note');assert.equal(out.summary.hasSeparatedBass,true);assert.equal(out.summary.hasSeparatedAccompaniment,false);assert.equal(event.sourceSeparated,true);assert.equal(event.instrumentSeparated,true);});
test('timeline rejects invalid duration',()=>assert.throws(()=>Timeline.build({duration:0}))); 
