'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
require('../web/analysis/stem-cache.js');const WavReader=require('../web/analysis/wav-reader.js'),config=require('../web/analysis/models/features.json'),{DownsampleWriter,header,validKey}=globalThis.LightForgeStemCache;
class Stream{constructor(){this.parts=[];this.closed=false;}async write(b){assert.equal(this.closed,false);this.parts.push(Buffer.from(b));}async close(){this.closed=true;}bytes(){return Buffer.concat(this.parts);}}
test('full-resolution writes preserve exact little-endian samples across bounded async buffer reuse',async()=>{const parts=[],buffers=new Set();const stream={async write(bytes){assert.ok(bytes.byteLength<=65536);buffers.add(bytes.buffer);await new Promise(r=>setImmediate(r));parts.push(Buffer.from(bytes));}};const writer=new globalThis.LightForgeStemCache.FloatWriter(stream),pcm=Float32Array.from({length:100003},(_,i)=>Math.sin(i)*1e-7);await writer.push(pcm.subarray(0,90001));await writer.push(pcm.subarray(90001));const expected=Buffer.alloc(pcm.length*4);for(let i=0;i<pcm.length;i++)expected.writeFloatLE(pcm[i],i*4);assert.deepEqual(Buffer.concat(parts),expected);assert.equal(buffers.size,1);await assert.rejects(writer.push(new Float32Array([NaN])),/Invalid full-resolution/);const broken=new globalThis.LightForgeStemCache.FloatWriter({async write(){throw Error('quota');}});await assert.rejects(broken.push(new Float32Array([1])),/quota/);});
function expected(pcm){const out=new Float32Array(Math.ceil(pcm.length/2));for(let i=0;i<out.length;i++){let value=0;for(let j=0;j<63;j++)value+=(pcm[i*2+j-31]||0)*config.resampleHalfFIR[j];out[i]=Number.isFinite(value)?value:0;}const b=Buffer.alloc(out.length*4);for(let i=0;i<out.length;i++)b.writeFloatLE(out[i],i*4);return b;}
async function write(pcm,chunks=[pcm.length]){const stream=new Stream(),writer=new DownsampleWriter(stream,config.resampleHalfFIR,pcm.length);let at=0,k=0,maxBuffer=0;while(at<pcm.length){const n=Math.min(pcm.length-at,chunks[k++%chunks.length]);await writer.push(pcm.subarray(at,at+n),at);at+=n;maxBuffer=Math.max(maxBuffer,writer.buffer.length);}await writer.finish();return {bytes:stream.bytes(),writer,stream,maxBuffer};}
function pcmFixture(n=110251){let seed=0x287;return Float32Array.from({length:n},(_,i)=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return .4*Math.sin(2*Math.PI*1073*i/44100)+.01*(seed/4294967296-.5);});}
test('odd contiguous input chunks equal the independent centered 63-tap convolution exactly',async()=>{assert.equal(config.resampleHalfFIR.length,63);const pcm=pcmFixture(),reference=expected(pcm),whole=await write(pcm),chunked=await write(pcm,[1,3,17,109,4093,22049,71]);assert.deepEqual(whole.bytes,reference);assert.deepEqual(chunked.bytes,reference);assert.equal(chunked.writer.next,Math.ceil(pcm.length/2));assert.equal(chunked.bytes.length,Math.ceil(pcm.length/2)*4);assert.equal(chunked.stream.closed,true);assert.ok(chunked.maxBuffer<=63);});
test('an impulse remains on its original sample clock without FIR group-delay shift',async()=>{const pcm=new Float32Array(44101),at=20000;pcm[at]=1;const {bytes}=await write(pcm,[1,701,1803]),values=new Float32Array(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.length));let peak=0;for(let i=0;i<values.length;i++)if(Math.abs(values[i])>Math.abs(values[peak]))peak=i;assert.equal(peak,at/2);assert.equal(values[peak],Math.fround(config.resampleHalfFIR[31]));assert.ok(Math.abs(peak/22050-at/44100)<1e-12);});
test('floating-point stems retain very quiet audio below PCM16 resolution',async()=>{const pcm=Float32Array.from({length:44101},(_,i)=>1e-8*Math.sin(2*Math.PI*317*i/44100)),{bytes}=await write(pcm,[149,701]),reference=expected(pcm);assert.deepEqual(bytes,reference);let max=0;for(let i=0;i<bytes.length;i+=4)max=Math.max(max,Math.abs(bytes.readFloatLE(i)));assert.ok(max>9e-9&&max<1.01e-8);});
test('one-sample and odd tails are flushed once with exact ceil(N/2) output',async()=>{for(const n of [1,2,3,31,32,33,62,63,64,65,44101]){const pcm=new Float32Array(n);pcm[n-1]=.5;const out=await write(pcm,[1,7,13]);assert.deepEqual(out.bytes,expected(pcm));assert.equal(out.bytes.length,Math.ceil(n/2)*4);assert.equal(out.writer.next,Math.ceil(n/2));}});
test('out-of-order, oversized and incomplete writer input rejects without closing incomplete audio',async()=>{const stream=new Stream(),writer=new DownsampleWriter(stream,config.resampleHalfFIR,100);await assert.rejects(writer.push(new Float32Array(3),1),/out of sequence/);await writer.push(new Float32Array(3),0);await assert.rejects(writer.push(new Float32Array(3),0),/out of sequence/);await assert.rejects(writer.push(new Float32Array(98),3),/out of sequence/);await assert.rejects(writer.finish(),/ended before/);assert.equal(stream.closed,false);});
test('stream write failures propagate to cache transaction cleanup',async()=>{const writer=new DownsampleWriter({async write(){throw Error('simulated quota');}},config.resampleHalfFIR,100);await assert.rejects(writer.push(new Float32Array(100),0),/simulated quota/);});
test('cache WAV header is mono 22.05 kHz IEEE float with exact byte counts',()=>{const b=Buffer.from(header(22051));assert.equal(b.toString('ascii',0,4),'RIFF');assert.equal(b.toString('ascii',8,16),'WAVEfmt ');assert.equal(b.readUInt32LE(4),36+22051*4);assert.equal(b.readUInt16LE(20),3);assert.equal(b.readUInt16LE(22),1);assert.equal(b.readUInt32LE(24),22050);assert.equal(b.readUInt32LE(28),88200);assert.equal(b.readUInt16LE(32),4);assert.equal(b.readUInt16LE(34),32);assert.equal(b.readUInt32LE(40),22051*4);assert.equal(validKey('stem-11111111-1111-1111-1111-111111111111'),true);for(const k of ['../voice','stem-/../../x','',null,undefined])assert.equal(validKey(k),false);});

function wav({bits=16,format=1,channels=2,rate=44100,samples=rate,values=[]}={}){const align=channels*bits/8,b=Buffer.alloc(44+samples*align);b.write('RIFF',0);b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(format,20);b.writeUInt16LE(channels,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*align,28);b.writeUInt16LE(align,32);b.writeUInt16LE(bits,34);b.write('data',36);b.writeUInt32LE(samples*align,40);for(let i=0;i<Math.min(samples,values.length);i++)for(let c=0;c<channels;c++){const x=values[i][c]??values[i][0],at=44+i*align+c*bits/8;if(format===3)b.writeFloatLE(x,at);else if(bits===16)b.writeInt16LE(x,at);else if(bits===24)b.writeIntLE(x,at,3);else b.writeInt32LE(x,at);}return b;}
async function reader(b){const r=new WavReader('');r.bytes=async(start,end)=>{r.totalBytes=b.length;const s=b.subarray(start,end+1);return s.buffer.slice(s.byteOffset,s.byteOffset+s.byteLength);};await r.open();return r;}
for(const bits of [16,24,32])test(`stereo44100 decodes signed PCM${bits} independently for left and right`,async()=>{const max=2**(bits-1),values=[[-max,max-1],[max/4,-max/2],[0,1]],r=await reader(wav({bits,values})),[l,rr]=await r.stereo44100(0,3);for(let i=0;i<3;i++){assert.equal(l[i],Math.fround(values[i][0]/max));assert.equal(rr[i],Math.fround(values[i][1]/max));}});
test('stereo44100 preserves float channels and silences non-finite samples',async()=>{const values=[[.00000001,-.25],[NaN,Infinity],[-Infinity,.875]],r=await reader(wav({bits:32,format:3,values})),[l,rr]=await r.stereo44100(0,3);assert.deepEqual(Array.from(l),[Math.fround(1e-8),0,0]);assert.deepEqual(Array.from(rr),[-.25,0,.875]);});
test('stereo44100 duplicates mono and uses the first two channels of multichannel PCM',async()=>{const mono=await reader(wav({channels:1,values:[[8192],[-16384]]})),m=await mono.stereo44100(0,2);assert.deepEqual(m[0],m[1]);const surround=await reader(wav({channels:6,values:[[8192,-16384,1000,2000,3000,4000]]})),s=await surround.stereo44100(0,1);assert.equal(s[0][0],.25);assert.equal(s[1][0],-.5);});
test('negative and out-of-track stereo reads zero-pad exactly without moving audible samples',async()=>{const b=wav({values:[[8192,-16384],[16384,-8192]]});b.writeInt16LE(4096,b.length-4);b.writeInt16LE(-4096,b.length-2);const r=await reader(b),start=await r.stereo44100(-2,5),end=await r.stereo44100(44099,4);assert.deepEqual(Array.from(start[0]),[0,0,.25,.5,0]);assert.deepEqual(Array.from(start[1]),[0,0,-.5,-.25,0]);assert.deepEqual(Array.from(end[0]),[.125,0,0,0]);assert.deepEqual(Array.from(end[1]),[-.125,0,0,0]);assert.ok((await r.stereo44100(-100,3)).every(a=>a.every(x=>x===0)));assert.ok((await r.stereo44100(999999,3)).every(a=>a.every(x=>x===0)));});
test('stereo input validates limits, rejects wrong sample rates and detects truncated transfers',async()=>{const r=await reader(wav());for(const [start,count]of [[.5,2],[0,-1],[0,Infinity],[0,44100*40+1]])await assert.rejects(r.stereo44100(start,count),/Invalid stereo/);assert.equal((await r.stereo44100(0,0))[0].length,0);const proxy=await reader(wav({rate:22050}));await assert.rejects(proxy.stereo44100(0,10),/original 44.1/);r.bytes=async()=>new ArrayBuffer(3);await assert.rejects(r.stereo44100(0,3),/incomplete/);const truncated=wav().subarray(0,100);await assert.rejects(reader(truncated),/incomplete/);});
