'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
require('../web/analysis/dsp.js');const {Extractor,summarize}=require('../web/analysis/vocal-detail.js');
const RATE=44100;
function fixture(duration=8){return {duration,pcm:new Float32Array(Math.ceil(duration*RATE)),residual:new Float32Array(Math.ceil(duration*RATE))};}
function voice(f,start,end,frequency,amplitude=.18,{vibrato=0,articulation=[]}={}){let phase=0;for(let i=Math.ceil(start*RATE);i<Math.min(f.pcm.length,end*RATE);i++){const time=i/RATE,t=time-start,hz=frequency*2**(vibrato*Math.sin(2*Math.PI*5.3*t)/12);phase+=2*Math.PI*hz/RATE;let shape=Math.min(1,t/.014,(end-time)/.026);for(const at of articulation){const d=time-at;if(d>-.11&&d<0)shape*=.2+.8*(-d/.11);else if(d>=0&&d<.06)shape*=.2+.8*d/.06;}f.pcm[i]+=amplitude*shape*(.5*Math.sin(phase)+.25*Math.sin(2*phase)+.16*Math.sin(3*phase)+.09*Math.sin(4*phase));}}
function scores(duration,singing=.8,speech=.01){return {singingScores:new Float32Array(Math.ceil(duration/.04)).fill(singing),speechScores:new Float32Array(Math.ceil(duration/.04)).fill(speech),frameStep:.04};}
function analyze(f,classifier=scores(f.duration),chunk=RATE){const e=new Extractor({duration:f.duration});for(let at=0;at<f.pcm.length;at+=chunk)e.push(f.pcm.subarray(at,at+chunk),at,f.residual.subarray(at,at+chunk));return e.finish({classifier,model:{id:'synthetic-fixture-truth',name:'No model inference in this DSP fixture'}});}
test('isolated off-grid phrase edges and held pitches remain on the vocal clock',()=>{const f=fixture(),truth=[[.637,2.213,164.814],[3.317,4.483,246.942],[5.339,7.157,98]];for(const n of truth)voice(f,...n);const out=analyze(f);assert.equal(out.phrases.length,3);assert.equal(out.notes.length,3);for(let i=0;i<3;i++){assert.ok(Math.abs(out.phrases[i].start-truth[i][0])<=.025,JSON.stringify(out.phrases[i]));assert.ok(Math.abs(out.phrases[i].end-truth[i][1])<=.035);assert.ok(Math.abs(12*Math.log2(out.notes[i].frequency/truth[i][2]))<.15,JSON.stringify(out.notes[i]));assert.equal(out.notes[i].type,'held-note');}assert.equal(out.source,'separated-vocals');assert.equal(out.lyricsAligned,false);assert.equal(out.timing.gridIsAccuracy,false);});
test('quiet verse remains voiced after a chorus forty decibels louder',()=>{const f=fixture(20);voice(f,.617,3.217,220,.35);voice(f,12.173,15.363,164.814,.0035);const out=analyze(f);assert.equal(out.phrases.length,2);assert.ok(Math.abs(out.phrases[1].start-12.173)<.04);assert.ok(out.notes.some(n=>n.start>12&&n.end>15));assert.ok(Math.max(...out.envelope.slice(610,750))>.5);});
test('local normalization recovers an immediately following quiet vocal phrase',()=>{const f=fixture(8);voice(f,.3,3.117,220,.35);voice(f,3.427,6.363,164.814,.0035);const out=analyze(f);assert.equal(out.phrases.length,2);assert.ok(Math.abs(out.phrases[1].start-3.427)<.04,JSON.stringify(out.phrases));assert.ok(out.notes.some(n=>n.start<3.55&&n.end>6));assert.ok(Math.max(...out.envelope.slice(190,270))>.4);});
test('vibrato sustains stay musical and source articulations do not follow accompaniment kicks',()=>{const f=fixture(7);voice(f,.733,6.273,196,.2,{vibrato:.35,articulation:[1.537,3.173,4.437]});for(const at of [1.437,3.073,4.337])for(let i=Math.floor(at*RATE);i<Math.min(f.residual.length,(at+.2)*RATE);i++){const t=i/RATE-at;f.residual[i]+=.9*Math.sin(2*Math.PI*80*t)*Math.exp(-20*t);}const out=analyze(f);assert.equal(out.phrases.length,1);for(const at of [1.537,3.173,4.437])assert.ok(out.accents.some(a=>a.time>=at-.025&&a.time<at+.095),JSON.stringify(out.accents));assert.ok(out.notes.some(n=>n.end-n.start>1));assert.ok(out.notes.every(n=>Math.abs(n.midi-55)<.6));});
test('speech is represented as voice phrasing without invented sung notes',()=>{const f=fixture(4);voice(f,.583,3.127,127);const out=analyze(f,scores(4,.03,.9));assert.equal(out.phrases.length,1);assert.equal(out.phrases[0].kind,'speech');assert.equal(out.notes.length,0);assert.equal(out.pitchContour.midi.filter(x=>x).length,0);});
test('harmonic instrumental leakage without learned voice evidence is rejected',()=>{const f=fixture(5);voice(f,.3,4.7,220,.03);for(let i=0;i<f.residual.length;i++)f.residual[i]=Math.sin(2*Math.PI*110*i/RATE)*.5;const out=analyze(f,scores(5,.003,.002));assert.equal(out.phrases.length,0);assert.equal(out.notes.length,0);assert.equal(out.accents.length,0);assert.equal(out.presence,'not_detected');});
test('quiet instrumental leakage is not amplified into voice by uncertain contextual scores',()=>{const f=fixture(6);voice(f,.1,5.9,220,.007);for(let i=0;i<f.residual.length;i++)f.residual[i]=.4*Math.sin(2*Math.PI*110*i/RATE);const out=analyze(f,scores(6,.21,.01));assert.equal(out.phrases.length,0);assert.equal(out.notes.length,0);assert.equal(out.accents.length,0);});
test('an isolated aperiodic vocal source can retain uncertain phrasing with weak semantic evidence',()=>{const f=fixture(8),truth=[[1.317,3.113],[4.317,6.713]];let seed=881;for(let i=0;i<f.pcm.length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const time=i/RATE,phrase=truth.find(([a,b])=>time>=a&&time<b),noise=2*seed/4294967296-1;f.pcm[i]=noise*(phrase?.2*Math.min(1,(time-phrase[0])/.012,(phrase[1]-time)/.025):.0003);f.residual[i]=.3*Math.sin(2*Math.PI*110*time);}const out=analyze(f,scores(8,.045,.01));assert.equal(out.phrases.length,2);assert.equal(out.presence,'uncertain');assert.equal(out.notes.length,0);assert.ok(out.phrases.every(p=>p.kind==='vocal'&&p.evidenceMode==='separation-led'));for(let i=0;i<2;i++){assert.ok(Math.abs(out.phrases[i].start-truth[i][0])<.04);assert.ok(Math.abs(out.phrases[i].end-truth[i][1])<.04);}assert.ok(out.accents.length>=2);});
test('a strong separated harmonic source without a semantic voice seed remains unclassified',()=>{const f=fixture(5);voice(f,.217,4.793,246.942,.3);const out=analyze(f,scores(5,.001,.001));assert.equal(out.phrases.length,0);assert.equal(out.notes.length,0);assert.equal(out.presence,'not_detected');});
test('silence and stochastic vocal-stem noise cannot invent periodic sung notes',()=>{const quiet=analyze(fixture(2));assert.equal(quiet.phrases.length,0);const f=fixture(4);let seed=10;for(let i=0;i<f.pcm.length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;f.pcm[i]=.1*(2*seed/4294967296-1);}const out=analyze(f,scores(4,.8));assert.equal(out.notes.length,0);});
test('streaming chunk boundaries preserve all musical results exactly',()=>{const f=fixture(12);voice(f,.019,1.789,146.832);voice(f,3.977,5.123,329.628,.04);voice(f,9.937,11.999,87.307,.3,{vibrato:.3});const a=analyze(f,scores(12),RATE*3),b=analyze(f,scores(12),13571);delete a.diagnostics.maxBufferedPcmSamples;delete b.diagnostics.maxBufferedPcmSamples;assert.deepEqual(a,b);});
test('the 22.05 kHz source-cache path preserves vocal note pitches and timing',()=>{const f=fixture(5);voice(f,.613,3.217,164.814);const pcm=Float32Array.from({length:Math.ceil(f.pcm.length/2)},(_,i)=>f.pcm[i*2]),extractor=new Extractor({sampleRate:22050,duration:5});for(let at=0;at<pcm.length;at+=13717)extractor.push(pcm.subarray(at,at+13717),at);const out=extractor.finish({classifier:scores(5)});assert.equal(out.phrases.length,1);assert.equal(out.notes.length,1);assert.ok(Math.abs(out.phrases[0].start-.613)<.025);assert.ok(Math.abs(out.notes[0].frequency-164.814)<2);});
test('streaming rejects missing samples, overlaps, non-finite audio and rate mistakes',()=>{assert.throws(()=>new Extractor({duration:2,sampleRate:48000}),/22.05/);const e=new Extractor({duration:2});assert.throws(()=>e.push(new Float32Array(10),1),/contiguous/);assert.throws(()=>e.push(Float32Array.of(NaN),0),/invalid/);e.push(new Float32Array(100),0);assert.throws(()=>e.push(new Float32Array(1),99),/contiguous/);assert.throws(()=>e.finish(),/ended/);});
test('short and endpoint audio are finite without invented padding',()=>{const f=fixture(.113);voice(f,0,.113,440);const out=analyze(f);assert.ok(out.phrases.every(p=>p.start>=0&&p.end<=f.duration));assert.equal(out.envelope.length,Math.ceil(f.duration/.02));assert.ok(out.envelope.every(Number.isFinite));assert.doesNotThrow(()=>JSON.stringify(out));});
test('minimum-length note eligibility does not depend on floating-point timestamp rounding',()=>{const duration=14,n=duration/.02,frequency=Float32Array.from({length:n},(_,i)=>Math.floor(i/7)%2?246.942:220),periodicity=new Float32Array(n).fill(.92),fineEnergy=new Float32Array(n*4).fill(.2),out=summarize({duration,frequency,periodicity,fineEnergy},{classifier:scores(duration)});assert.equal(out.notes.length,100);assert.ok(out.notes.every(n=>Math.abs(n.end-n.start-.14)<1e-8));});
test('four-hour summaries retain bounded numeric arrays and avoid argument spreading',()=>{const duration=14400,fineEnergy=new Float32Array(Math.ceil(duration/.005)),frequency=new Float32Array(Math.ceil(duration/.02)),periodicity=new Float32Array(frequency.length),out=summarize({duration,fineEnergy,frequency,periodicity},{classifier:scores(duration,0,0)});assert.equal(out.phrases.length,0);assert.equal(out.envelope.length,720000);assert.equal(out.pitchContour.midi.length,360000);assert.ok(Buffer.byteLength(JSON.stringify(out))<8*1024*1024);});
