'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Reader=require('../web/analysis/wav-reader.js');
function record(){const events=[],active=[];return {events,active,measure(name,fn){assert.equal(active.length,0);active.push(name);try{return fn();}finally{active.pop();events.push(name);}}};}
function wave({rate=22050,bits=16,format=1,channels=2}={}){const stride=channels*bits/8,b=Buffer.alloc(44+rate*stride);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(format,20);b.writeUInt16LE(channels,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*stride,28);b.writeUInt16LE(stride,32);b.writeUInt16LE(bits,34);b.write('data',36);b.writeUInt32LE(rate*stride,40);for(let i=0;i<rate;i++)for(let c=0;c<channels;c++){const p=44+i*stride+c*bits/8,value=Math.sin(i*.13)*(c?-.2:.7);if(format===3)b.writeFloatLE(i===11?NaN:value,p);else if(bits===16)b.writeInt16LE(Math.round(value*32767),p);else if(bits===24)b.writeIntLE(Math.round(value*8388607),p,3);else b.writeInt32LE(Math.round(value*2147483647),p);}return b;}
async function open(ReaderType,bytes,telemetry){const reader=new ReaderType('/fixture.wav',telemetry);reader.totalBytes=bytes.length;reader.bytes=async(start,end)=>{assert.equal(telemetry?.active.length||0,0,'IO must not be included in decode/resample timing');await Promise.resolve();const b=bytes.subarray(start,Math.min(bytes.length,end+1));return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);};await reader.open();return reader;}
test('WAV parsing and IO are outside PCM decoding; factor1 performs no resampling stage',async()=>{const telemetry=record(),reader=await open(Reader,wave(),telemetry);assert.equal(telemetry.events.length,0);const out=await reader.mono22050(-8,40,{});assert.equal(out.length,40);assert.ok(out.subarray(0,8).every(x=>x===0));assert.deepEqual(telemetry.events,['performance.audio_decode']);});
test('44.1kHz mono FIR and stereo decoding record distinct actual loops for each PCM representation',async()=>{for(const [bits,format] of [[16,1],[24,1],[32,1],[32,3]]){const telemetry=record(),reader=await open(Reader,wave({rate:44100,bits,format}),telemetry),config={resampleHalfFIR:new Float64Array(63).fill(1/63)};const mono=await reader.mono22050(-5,64,config);assert.ok(mono.every(Number.isFinite));assert.deepEqual(telemetry.events,['performance.audio_decode','performance.resample_normalize']);telemetry.events.length=0;const stereo=await reader.stereo44100(-5,64);assert.ok(stereo.every(x=>x.every(Number.isFinite)));assert.deepEqual(telemetry.events,['performance.audio_decode']);}});
test('unsupported stereo or wholly padded reads do not invent decode observations',async()=>{const telemetry=record(),reader=await open(Reader,wave(),telemetry);await assert.rejects(reader.stereo44100(0,64),/44.1 kHz/);await reader.mono22050(-100,10,{});assert.equal(telemetry.events.length,0);});
test('transport failures occur before decode probes',async()=>{const telemetry=record(),reader=await open(Reader,wave(),telemetry);reader.bytes=async()=>{throw new Error('fixture IO failure');};await assert.rejects(reader.mono22050(0,32,{}),/fixture IO failure/);assert.equal(telemetry.events.length,0);});
module.exports={wave,open,record};

test('zero-length requested resampling records no FIR execution',async()=>{const telemetry=record(),reader=await open(Reader,wave({rate:44100}),telemetry);const out=await reader.mono22050(0,0,{resampleHalfFIR:new Float64Array(63).fill(1/63)});assert.equal(out.length,0);assert.equal(telemetry.events.includes('performance.resample_normalize'),false);});
