"""Create exact leading/trailing digital silence around a real singing excerpt.
Source sung.wav is regenerated by the vocal fixture acquisition program.
"""
from pathlib import Path
import wave,json
root=Path(__file__).resolve().parent;p=root/'vocal-fixtures'
with wave.open(str(p/'sung.wav'),'rb') as w:
 sr=w.getframerate();assert w.getnchannels()==1 and w.getsampwidth()==2
 w.setpos(sr*15);part=w.readframes(round(sr*5.2))
lead=round(sr*3.13);tail=round(sr*11.7)
with wave.open(str(p/'voice-edge-case.wav'),'wb') as w:
 w.setnchannels(1);w.setsampwidth(2);w.setframerate(sr);w.writeframes(bytes(lead*2)+part+bytes(tail*2))
(root/'vocal-edge-case-fixture.json').write_text(json.dumps({'leadingSilentUntil':lead/sr,'nonzeroAudioUntil':lead/sr+len(part)/(sr*2),'duration':(lead+len(part)/2+tail)/sr,'source':'sung.wav,15s..20.2s','meaning':'Known exact digital-silence bounds; interior singing labels not manually annotated'},indent=2)+'\n')
