/* Real Chromium Worker/IndexedDB integration. Native bridge is explicitly a transport mock. */
const {chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),assert=require('assert'),cp=require('child_process'),crypto=require('crypto'),path=require('path'),zlib=require('zlib');
const root=path.resolve(__dirname,'../..'),outDir=__dirname,origin='http://127.0.0.1:8892';
const files=['web/app.js','web/engine/client.js','web/engine/worker.js','web/engine/show-engine.js','web/engine/light-planner.js','web/engine/movement-planner.js','web/engine/vehicle-profile.js','web/studio-tools.js','web/music-insights.js','web/index.html','web/styles.css'];
const hashes=()=>Object.fromEntries(files.map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(root+'/'+p)).digest('hex')]));
async function ready(page){await page.waitForFunction(()=>window.LightForgeApp&&window.ShowCompiler&&!LightForgeApp.state.loadingProject&&!LightForgeApp.state.composing,{},{timeout:45000});}
(async()=>{const sourceHashes=hashes(),server=cp.spawn('python3',['-m','http.server','8892','--bind','127.0.0.1','--directory',root+'/web'],{stdio:'ignore'});let browser;const out={release:'1.5.0',scope:'Desktop Chromium actual dedicated Web Workers, gzip/WebCrypto and IndexedDB; native export bridge is a mock, no Android runtime or vehicle test.',checks:[],errors:[]};try{
 await new Promise(r=>setTimeout(r,350));browser=await chromium.launch({executablePath:'/workspace/scratch/9b34d7a394e6/app/toolchain/chrome/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:393,height:852},reducedMotion:'reduce'});page.on('pageerror',e=>out.errors.push(e.message));await page.addInitScript(()=>{
  // Rendering has its own actual WebGL suite; isolate composition responsiveness here.
  const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return String(type).includes('webgl')?null:original.call(this,type,...args);};
  window.testCanonical=value=>JSON.stringify(value,(key,item)=>item&&typeof item==='object'&&!Array.isArray(item)?Object.fromEntries(Object.keys(item).sort().map(k=>[k,item[k]])):item);
  window.testDigest=async bytes=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');
  window.testMusic=(duration=64)=>({duration,bpm:120,analysisVersion:4,beatConfidence:1,meter:4,meterConfidence:.95,beats:Array.from({length:Math.ceil(duration*2)},(_,i)=>i*.5),downbeats:Array.from({length:Math.ceil(duration/2)},(_,i)=>i*2),onsets:Array.from({length:Math.ceil(duration*2)},(_,i)=>({time:i*.5,strength:.7,band:i%2?'high':'bass'})),sections:[{start:0,end:duration,energy:.6,label:'Fixture'}],energy:Array.from({length:Math.ceil(duration/.02)},()=>.6),energyStep:.02,waveform:Array.from({length:512},()=>.6),engine:{name:'Annotated runtime fixture',neural:false}});
  window.testDB=async(store,key,value)=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('lightforge',1);r.onupgradeneeded=()=>{r.result.createObjectStore('audio');r.result.createObjectStore('projects');};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});return new Promise((resolve,reject)=>{const tx=db.transaction(store,value===undefined?'readonly':'readwrite'),s=tx.objectStore(store),r=value===undefined?s.get(key):s.put(value,key);let result;r.onsuccess=()=>result=r.result;tx.oncomplete=()=>{db.close();resolve(result);};tx.onerror=()=>{db.close();reject(tx.error);};});};
 });await page.goto(origin);await ready(page);
 const legacyFixture=JSON.parse(fs.readFileSync(outDir+'/legacy-1.4-project.json','utf8'));
 const legacyHeader=Buffer.from(legacyFixture.expectedHeader),producerOffset=legacyHeader.indexOf(Buffer.from('LightForge 1.4.0'));assert(producerOffset>=0);const migratedHeader=Buffer.from(legacyHeader);migratedHeader.set(Buffer.from('LightForge 1.5.0'),producerOffset);const expectedMigratedFseqHash=crypto.createHash('sha256').update(migratedHeader).update(zlib.gunzipSync(Buffer.from(legacyFixture.compiled.frameData,'base64'))).digest('hex');
 out.legacyMigration=await page.evaluate(async fixture=>{const a=LightForgeApp,p={id:fixture.projectId,name:fixture.name,duration:fixture.music.duration,createdAt:Date.now(),audioUrl:'demo/glass-castle.wav',browser:true};a.state.projects=[p];localStorage.setItem('lightforge-projects',JSON.stringify([p]));await testDB('audio',p.id,await(await fetch('demo/glass-castle.wav')).blob());await testDB('projects',p.id,fixture);await a.selectProject(p,false);await a.saveProject();return{frameHash:await testDigest(a.state.show.frames),fseqHash:await testDigest(ShowEngine.fseq(a.state.show)),header:Array.from(ShowEngine.fseqHeader(a.state.show)),migration:a.state.compiled.settingsMigration,vocalFocus:a.state.settings.vocalFocus,bassFocus:a.state.settings.bassFocus,engine:a.state.show.version,analysis:a.state.music.analysisVersion,valid:a.state.show.validation.valid};},legacyFixture);
 assert.equal(out.legacyMigration.frameHash,legacyFixture.compiled.sha256);assert.equal(out.legacyMigration.fseqHash,expectedMigratedFseqHash);assert.deepStrictEqual(out.legacyMigration.header,Array.from(migratedHeader));assert.equal(out.legacyMigration.vocalFocus,.85);assert.equal(out.legacyMigration.bassFocus,.9);assert(out.legacyMigration.migration.framesPreserved&&out.legacyMigration.valid);assert.equal(out.legacyMigration.engine,'1.4.0');assert.equal(out.legacyMigration.analysis,3);
 await page.reload();await ready(page);await page.waitForFunction(()=>!!LightForgeApp.state.show);
 const migratedAgain=await page.evaluate(async()=>{const a=LightForgeApp;return{frames:await testDigest(a.state.show.frames),fseq:await testDigest(ShowEngine.fseq(a.state.show)),saved:(await testDB('projects',a.state.project.id)).compiled.sha256};});assert.equal(migratedAgain.frames,legacyFixture.compiled.sha256);assert.equal(migratedAgain.fseq,expectedMigratedFseqHash);assert.equal(migratedAgain.saved,legacyFixture.compiled.sha256);
 out.legacyMigration.rejectedEdits=await page.evaluate(async fixture=>{const results={};for(const [name,patch]of Object.entries({oldSetting:{intensity:.1},newSetting:{vocalFocus:.2},differentBass:{bassFocus:.2}})){try{await ShowCompiler.restore(fixture.compiled,fixture.music,{...fixture.settings,vocalFocus:.85,bassFocus:.9,...patch});results[name]=false;}catch(e){results[name]=/match its music and edits/.test(e.message);}}return results;},legacyFixture);assert.deepStrictEqual(out.legacyMigration.rejectedEdits,{oldSetting:true,newSetting:true,differentBass:true});out.checks.push('An arrangement compiled by the actual archived 1.4 worker opens through production project loading, gains only new default focus keys, preserves exact original frames, and changes only the FSEQ producer version in its header. A second 1.5 reopen is byte-identical. Altered legacy or focus settings cannot bypass input integrity.');
 await page.evaluate(async()=>{const a=LightForgeApp,p={id:'runtime-fixture',name:'Runtime fixture',duration:64,createdAt:Date.now(),audioUrl:'demo/glass-castle.wav',browser:true};a.state.projects=[p];localStorage.setItem('lightforge-projects',JSON.stringify([p]));await a.selectProject(p,true);await testDB('audio',p.id,await(await fetch('demo/glass-castle.wav')).blob());a.state.music=testMusic();a.state.settings.dance='off';await a.regenerate({save:false});});await ready(page);
 out.roundtrip=await page.evaluate(async()=>{const a=LightForgeApp,restored=await ShowCompiler.restore(a.state.compiled,a.state.music,a.state.settings);return{original:await testDigest(a.state.show.frames),restored:await testDigest(restored.show.frames),valid:restored.show.validation.valid,header:Array.from(restored.header),compressedCharacters:a.state.compiled.frameData.length,rawBytes:a.state.show.frames.length,previewIndex:restored.show.previewIndex.version};});assert.equal(out.roundtrip.original,out.roundtrip.restored);assert(out.roundtrip.valid);assert.equal(String.fromCharCode(...out.roundtrip.header.slice(0,4)),'PSEQ');out.checks.push('Actual worker gzip roundtrip preserves every frame, validates the show and returns its checked FSEQ header.');
 out.jsonKeyOrder=await page.evaluate(async()=>{const a=LightForgeApp;const reorder=value=>Array.isArray(value)?value.map(reorder):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).reverse().map(k=>[k,reorder(value[k])])):value;const saved=reorder(JSON.parse(JSON.stringify(a.state.compiled))),music=reorder(JSON.parse(JSON.stringify(a.state.music))),settings=reorder(JSON.parse(JSON.stringify(a.state.settings)));const restored=await ShowCompiler.restore(saved,music,settings);return{valid:restored.show.validation.valid,frameHash:await testDigest(restored.show.frames),expectedHash:a.state.compiled.sha256};});assert(out.jsonKeyOrder.valid);assert.equal(out.jsonKeyOrder.frameHash,out.jsonKeyOrder.expectedHash);out.checks.push('Reordering every JSON object across project metadata, analysis and settings preserves the verified arrangement; array order remains intact.');
 out.integrity=await page.evaluate(async()=>{const a=LightForgeApp,base=a.state.compiled,results={};async function rejects(name,change,settings=a.state.settings){const c=JSON.parse(JSON.stringify(base));change(c);try{await ShowCompiler.restore(c,a.state.music,settings);results[name]={rejected:false};}catch(e){results[name]={rejected:true,message:e.message};}}
  await rejects('inputMismatch',()=>{},{...a.state.settings,intensity:.1});await rejects('frameChecksum',c=>c.sha256='0'.repeat(64));await rejects('metadataChecksum',c=>c.meta.vehicle='Different vehicle');await rejects('gzipCorruption',c=>c.frameData='invalid gzip');await rejects('expandedOversize',c=>c.frameCount--);await rejects('expandedUndersize',c=>c.frameCount++);
  const c=JSON.parse(JSON.stringify(base));c.meta.previewIndex={version:ShowEngine.version,frameCount:c.frameCount,stepMs:c.stepMs,lights:[],closures:[]};c.metaSHA256=await testDigest(new TextEncoder().encode(testCanonical(c.meta)));const clean=await ShowCompiler.restore(c,a.state.music,a.state.settings),expected=ShowEngine.stateAt(a.state.show,1.5),actual=ShowEngine.stateAt(clean.show,1.5);results.forgedIndex={rebuilt:clean.show.previewIndex.lights.length>0,lightValuesMatch:JSON.stringify(Array.from(actual.lights))===JSON.stringify(Array.from(expected.lights)),closureValuesMatch:JSON.stringify(actual.closures)===JSON.stringify(expected.closures)};return results;});for(const [k,v]of Object.entries(out.integrity))if(k!=='forgedIndex')assert(v.rejected,k);assert.deepStrictEqual(out.integrity.forgedIndex,{rebuilt:true,lightValuesMatch:true,closureValuesMatch:true});out.checks.push('Input/frame/metadata/gzip corruption and over/under expansion are rejected; imported preview caches are discarded even if their metadata hash is recomputed.');
 out.workerCancellation=await page.evaluate(async()=>{const a=LightForgeApp,controller=new AbortController();let progressSeen=false;const start=performance.now();try{await ShowCompiler.generate(testMusic(3600),a.state.settings,p=>{progressSeen=true;controller.abort();},controller.signal);return{rejected:false};}catch(e){return{rejected:e.name==='AbortError',progressSeen,elapsedMs:performance.now()-start};}});assert(out.workerCancellation.rejected&&out.workerCancellation.progressSeen);out.checks.push('Canceling an active worker after its first progress event rejects with AbortError and terminates that job.');
 out.workerResponsiveness=await page.evaluate(async()=>{const a=LightForgeApp;let prior=performance.now(),ticks=0,maxGap=0;const timer=setInterval(()=>{const now=performance.now();ticks++;maxGap=Math.max(maxGap,now-prior);prior=now;},16),start=performance.now();try{window.longMusic=testMusic(3600);window.longSettings=JSON.parse(JSON.stringify(a.state.settings));const r=await ShowCompiler.generate(longMusic,longSettings);window.longResult=r;return{durationSeconds:3600,frames:r.show.frameCount,frameBytes:r.show.frames.byteLength,valid:r.show.validation.valid,elapsedMs:performance.now()-start,heartbeatTicks:ticks,maxHeartbeatGapMs:maxGap,scope:'Desktop scheduler under concurrent build load; not Android timing.'};}finally{clearInterval(timer);}});assert(out.workerResponsiveness.valid);assert(out.workerResponsiveness.heartbeatTicks>=5);assert(out.workerResponsiveness.maxHeartbeatGapMs<1000);out.checks.push('One-hour synthetic composition completes in a worker while the interface heartbeat continues.');
 out.compressedHistory=await page.evaluate(async()=>{const a=LightForgeApp,original=a.state.project;await a.selectProject({id:'history-long',name:'Long history fixture',duration:3600,audioUrl:'demo/glass-castle.wav'},true);a.state.music=longMusic;a.state.settings=longSettings;a.state.show=longResult.show;a.state.compiled=longResult.compiled;a.state.exportHeader=longResult.header;a.state.showMusic=longMusic;a.state.renderedSettingsKey=JSON.stringify(longSettings);const saved=a.captureSnapshot(),frameHash=await testDigest(a.state.show.frames);a.state.show=null;a.state.compiled=null;await a.restoreSnapshot(saved,{recordHistory:false});const result={denseFramesOmitted:saved.show===null,compiledRetained:!!saved.compiled,bytes:longResult.show.frames.length,framesRestored:await testDigest(a.state.show.frames)===frameHash,ready:!document.getElementById('export').disabled};await a.selectProject(original,false);delete window.longResult;delete window.longMusic;delete window.longSettings;return result;});assert(out.compressedHistory.denseFramesOmitted&&out.compressedHistory.compiledRetained&&out.compressedHistory.framesRestored&&out.compressedHistory.ready);out.checks.push('Long-project history omits its 36 MB dense frame buffer and restores exact checked bytes from the retained gzip snapshot.');
 out.serializedEdits=await page.evaluate(async()=>{const a=LightForgeApp;const results=await Promise.allSettled([a.commitChannelSettings({tempoScale:2}),a.commitChannelSettings({meterOverride:3})]);return{statuses:results.map(x=>x.status),tempoScale:a.state.settings.tempoScale,meterOverride:a.state.settings.meterOverride,matching:a.state.renderedSettingsKey===JSON.stringify(a.state.settings)};});assert.deepStrictEqual(out.serializedEdits,{statuses:['fulfilled','fulfilled'],tempoScale:2,meterOverride:3,matching:true});out.checks.push('Concurrent independent edit requests serialize without dropping the first requested change.');
 await page.evaluate(async()=>{const a=LightForgeApp;await a.commitChannelSettings({tempoScale:1,meterOverride:null});document.querySelector('[data-style=cinematic]').click();document.querySelector('[data-dance=balanced]').click();});await ready(page);
 out.pendingUndo=await page.evaluate(async()=>{const a=LightForgeApp,pending=a.state.history.some(s=>s.show&&s.renderedSettingsKey!==JSON.stringify(s.settings));await a.undo();return{pendingSnapshotExisted:pending,style:a.state.settings.style,shownStyle:a.state.show.settings.style,matching:a.state.renderedSettingsKey===JSON.stringify(a.state.settings),exportEnabled:!document.getElementById('export').disabled};});assert(out.pendingUndo.pendingSnapshotExisted);assert.equal(out.pendingUndo.style,out.pendingUndo.shownStyle);assert(out.pendingUndo.matching&&out.pendingUndo.exportEnabled);out.checks.push('Undo of a snapshot captured between rapid direct settings changes rebuilds matching frames before enabling export.');
 out.nativeTransport=await page.evaluate(async()=>{const a=LightForgeApp,original=ShowEngine.fseqHeader,expectedHeader=Array.from(a.state.exportHeader);let chunks=[],meta,headerCalled=false;window.Android={pickAudio(){},saveProject(){return true;},beginExport(s){meta=JSON.parse(s);return JSON.stringify({id:'transport-test'});},appendExport(id,s){chunks.push(Uint8Array.from(atob(s),c=>c.charCodeAt(0)));return true;},finishExport(){window.onNativeEvent('exported',{id:'transport-test',name:'runtime.zip'});}};ShowEngine.fseqHeader=()=>{headerCalled=true;throw Error('Export must use the already checked worker header.');};try{await a.exportShow();const size=chunks.reduce((n,c)=>n+c.length,0),all=new Uint8Array(size);let p=0;for(const c of chunks){all.set(c,p);p+=c.length;}return{headerCalled,headerMatches:JSON.stringify(Array.from(all.slice(0,expectedHeader.length)))===JSON.stringify(expectedHeader),framesMatch:await testDigest(all.slice(expectedHeader.length))===await testDigest(a.state.show.frames),bytes:size,expectedBytes:expectedHeader.length+a.state.show.frames.length,projectId:meta?.projectId,busy:a.state.busy};}finally{ShowEngine.fseqHeader=original;delete window.Android;document.getElementById('exportSuccess').hidden=true;a.state.lastSaved=null;}});assert(!out.nativeTransport.headerCalled);assert(out.nativeTransport.headerMatches&&out.nativeTransport.framesMatch);assert.equal(out.nativeTransport.bytes,out.nativeTransport.expectedBytes);assert(!out.nativeTransport.busy);out.checks.push('Native transport mock receives checked header and exact frame bytes without calling the main-thread FSEQ validator.');
 const beforeReload=await page.evaluate(async()=>{const a=LightForgeApp;await a.saveProject();return{frameHash:await testDigest(a.state.show.frames),music:JSON.stringify(a.state.music),audioHash:await testDigest(await(await testDB('audio',a.state.project.id)).arrayBuffer()),compiledHash:a.state.compiled.sha256,settings:JSON.stringify(a.state.settings)};});await page.reload();await page.waitForFunction(()=>LightForgeApp?.state.show&&!LightForgeApp.state.composing&&!LightForgeApp.state.loadingProject,{},{timeout:45000});
 out.persistence=await page.evaluate(async()=>{const a=LightForgeApp;return{frameHash:await testDigest(a.state.show.frames),music:JSON.stringify(a.state.music),audioHash:await testDigest(await(await testDB('audio',a.state.project.id)).arrayBuffer()),compiledHash:a.state.compiled.sha256,settings:JSON.stringify(a.state.settings)};});assert.deepStrictEqual(out.persistence,beforeReload);delete out.persistence.music;out.checks.push('Autosave/reload restores the exact compiled arrangement, original analysis and imported audio bytes through actual IndexedDB.');
 // Opening a damaged saved copy must not erase the original evidence via the scheduled autosave.
 await page.evaluate(async()=>{await LightForgeApp.saveProject();const saved=await testDB('projects','runtime-fixture');saved.compiled.sha256='0'.repeat(64);await testDB('projects','runtime-fixture',saved);});await page.reload();await ready(page);await page.waitForTimeout(750);out.failedRestore=await page.evaluate(async()=>{const a=LightForgeApp;await a.saveProject();const saved=await testDB('projects','runtime-fixture');return{compiledRetained:!!saved.compiled,sha:saved.compiled?.sha256,showAdopted:!!a.state.show,exportDisabled:document.getElementById('export').disabled};});assert(out.failedRestore.compiledRetained);assert.equal(out.failedRestore.sha,'0'.repeat(64));assert(!out.failedRestore.showAdopted&&out.failedRestore.exportDisabled);out.checks.push('Opening a failed-checksum arrangement and then autosaving preserves the damaged saved copy for recovery and blocks export.');
 assert.deepStrictEqual(out.errors,[]);assert.deepStrictEqual(hashes(),sourceHashes,'Runtime source changed during verification; rerun against final source.');out.sourceHashes=sourceHashes;out.passed=true;fs.writeFileSync(outDir+'/runtime-verification.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
 }finally{await browser?.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
