#!/usr/bin/env python3
"""Verify a built release, then atomically publish APK and complete private source."""
from pathlib import Path
import hashlib,json,os,tempfile,zipfile

SIGNING_SHA256='7187d6aa935d5b7d2d656cb87913af95fe1ca3a4b1653036d1d8d890e2016c6b'
CHUNK_BYTES=1024*1024

def sha(data):return hashlib.sha256(data).hexdigest()
def sha_stream(stream):
 digest=hashlib.sha256()
 while True:
  chunk=stream.read(CHUNK_BYTES)
  if not chunk:break
  digest.update(chunk)
 return digest.hexdigest()
def sha_file(path):
 with path.open('rb') as stream:return sha_stream(stream)
def distributable(f,root):
 return f.is_file() and not any(v.startswith('.') or v in {'node_modules','__pycache__','classes'} for v in f.relative_to(root).parts)
def qa_distributable(f,root,qa_root):
 if not distributable(f,root):return False
 if any(v in {'fixtures','generated','node_modules','classes'} or v.endswith('-classes') or v.endswith('-fixtures') for v in f.relative_to(qa_root).parts):return False
 suffixes={'.java','.py','.js','.cjs','.mjs','.html','.json','.md','.txt','.png','.jpg','.webp'}
 if qa_root==root/'qa/release-1.6.0':suffixes.add('.log')
 return f.suffix in suffixes
def atomic(path,data):
 fd,name=tempfile.mkstemp(prefix='.'+path.name+'-',dir=path.parent)
 try:
  with os.fdopen(fd,'wb') as f:f.write(data);f.flush();os.fsync(f.fileno())
  os.replace(name,path)
 finally:
  if os.path.exists(name):os.unlink(name)
def require(condition,message):
 if not condition:raise SystemExit(message)
def streams_match(left,right):
 # Read each side with explicit bounds, retaining exact byte comparison.
 while True:
  a=left.read(CHUNK_BYTES);b=right.read(CHUNK_BYTES)
  if a!=b:return False
  if not a:return True

def atomic_copy(source,destination,expected_sha256):
 """Copy an already verified APK without retaining it in Python's heap."""
 fd,name=tempfile.mkstemp(prefix='.'+destination.name+'-',dir=destination.parent)
 digest=hashlib.sha256();size=0
 try:
  with os.fdopen(fd,'wb') as output,source.open('rb') as input:
   while True:
    chunk=input.read(CHUNK_BYTES)
    if not chunk:break
    output.write(chunk);digest.update(chunk);size+=len(chunk)
   output.flush();os.fsync(output.fileno())
  require(digest.hexdigest()==expected_sha256,'APK changed while publishing; the previous output was retained.')
  os.replace(name,destination)
  return {'path':str(destination),'bytes':size,'sha256':digest.hexdigest()}
 finally:
  if os.path.exists(name):os.unlink(name)

def stage_source_archive(destination,root,entries):
 """Return a CRC-checked temporary ZIP; caller publishes only after all checks.

 Entries are Path objects or small generated bytes. The manifest hashes the
 exact archived bytes, and a changed file aborts before atomic publication.
 """
 require(all(name.startswith(root) for name in entries),'Source entry is outside its archive root.')
 manifest_name=root+'SHA256SUMS.txt'
 require(manifest_name not in entries,'Source entries must not include a preexisting SHA256SUMS.txt.')
 hashes={name:sha(payload) if isinstance(payload,bytes) else sha_file(payload) for name,payload in sorted(entries.items())}
 manifest=''.join(hashes[name]+'  '+name[len(root):]+'\n' for name in sorted(entries)).encode()
 content=dict(entries);content[manifest_name]=manifest
 hashes[manifest_name]=sha(manifest)
 fd,name=tempfile.mkstemp(prefix='.'+destination.name+'-',dir=destination.parent)
 try:
  with os.fdopen(fd,'w+b') as output:
   with zipfile.ZipFile(output,'w',zipfile.ZIP_DEFLATED,compresslevel=6,allowZip64=True) as archive:
    for entry,payload in sorted(content.items()):
     info=zipfile.ZipInfo(entry);info.compress_type=zipfile.ZIP_DEFLATED
     info.external_attr=(0o100600 if '/signing/' in entry else 0o100644)<<16
     info.file_size=len(payload) if isinstance(payload,bytes) else payload.stat().st_size
     digest=hashlib.sha256()
     with archive.open(info,'w') as target:
      if isinstance(payload,bytes):
       target.write(payload);digest.update(payload)
      else:
       with payload.open('rb') as input:
        while True:
         chunk=input.read(CHUNK_BYTES)
         if not chunk:break
         target.write(chunk);digest.update(chunk)
     require(digest.hexdigest()==hashes[entry],'Source changed while packaging: '+entry)
   output.flush();os.fsync(output.fileno())
  temporary=Path(name)
  with zipfile.ZipFile(temporary) as archive:require(archive.testzip() is None,'Source archive ZIP CRC check failed.')
  return {'temporary_path':temporary,'bytes':temporary.stat().st_size,'sha256':sha_file(temporary),'entries':len(content)}
 except BaseException:
  if os.path.exists(name):os.unlink(name)
  raise

def main():
 p=Path(__file__).resolve().parents[1]
 version=json.loads((p/'version.json').read_text());VERSION=version['name'];VERSION_CODE=version['code']
 workspace=p.parents[1]
 out=workspace/'output';out.mkdir(exist_ok=True)
 apk=p/f'dist/LightForge-{VERSION}.apk'
 receipt=json.loads(apk.with_suffix('.apk.json').read_text())
 require(receipt.get('version_name')==VERSION and receipt.get('version_code')==VERSION_CODE,'Build the current release version before packaging.')
 require(all(receipt.get(k)==v for k,v in [('zip_integrity','passed'),('alignment','passed'),('signature','verified')]),'APK build checks did not pass.')
 signature=(p/'build/signature-verification.txt').read_text()
 require('Signer #1 certificate SHA-256 digest: '+SIGNING_SHA256 in signature,'Signing identity differs from the installed LightForge update key.')
 require(sha_file(apk)==receipt['sha256'],'APK checksum differs from its build receipt.')
 web=[f for f in (p/'web').rglob('*') if distributable(f,p/'web')]
 with zipfile.ZipFile(apk) as z:
  require(z.testzip() is None,'APK ZIP CRC check failed.')
  require(not any('node_modules' in name.split('/') for name in z.namelist()),'APK contains development dependencies.')
  for f in web:
   with z.open('assets/'+f.relative_to(p/'web').as_posix()) as asset,f.open('rb') as source:
    require(streams_match(asset,source),'APK asset differs from source: '+str(f.relative_to(p)))

 music_receipts=[f'qa/release-{VERSION}/'+name for name in [
  'analysis-verification.json','separator-verification.json','composer-verification.json','movement-verification.json',
  'light-verification.json','native-verification.json','runtime-verification.json',
  'integration-verification.json','studio16-verification.json','audition-verification.json',
  'preview-verification.json','role-composer-verification.json','bass-verification.json',
  'vocal-resampling-audit.json','vocal-detail-verification.json',
  'stem-cache-verification.json','migration-verification.json','build-integrity-verification.json'
 ]]
 current_receipts=music_receipts
 missing=[f for f in current_receipts if not (p/f).is_file()]
 require(not missing,'Current release evidence missing; finish validation before packaging: '+', '.join(missing))
 results={f:json.loads((p/f).read_text()) for f in current_receipts}
 for rel,result in results.items():
  require(result.get('passed') is not False, 'Current test receipt reports failure: '+rel)
  require(not result.get('errors'), 'Current test receipt has errors: '+rel)
  if 'release' in result:require(result['release']==VERSION,'Current receipt belongs to another release: '+rel)
  if rel in music_receipts:
   require(result.get('release')==VERSION and result.get('passed') is True,'Music verification must explicitly pass for '+VERSION+': '+rel)
   require(bool(result.get('source_hashes',result.get('sourceHashes'))),'Music verification must identify its tested production sources: '+rel)
  for source,digest in result.get('source_hashes',result.get('sourceHashes',{})).items():
   require((p/source).is_file() and sha_file(p/source)==digest,'Source changed since verification: '+source+' ('+rel+')')
 # Bind trained model evidence to the exact graphs delivered in this APK.
 model_receipt=results[f'qa/release-{VERSION}/analysis-verification.json']
 for name,details in model_receipt.get('models',{}).items():
  model=p/'web/analysis/models'/name
  require(model.is_file() and sha_file(model)==details['sha256'],'Model changed since runtime verification: '+name)
  require(model.stat().st_size==details['bytes'],'Model byte size changed: '+name)
 historical_paths={
  '1.5.0':'qa/release-1.6.0/historical-release-verification-1.5.0.json',
  '1.4.0':'qa/release-1.5.0/historical-release-verification-1.4.0.json',
  '1.3.0':'qa/release-1.4.0/historical-release-verification-1.3.0.json',
  '1.1.0':'qa/hardware-1.2.0/historical-release-verification-1.1.0.json',
  '1.2.0':'qa/music-1.3.0/historical-release-verification-1.2.0.json'
 }
 historical={}
 for version,rel in historical_paths.items():
  require((p/rel).is_file(),'Historical '+version+' receipt snapshot is missing.')
  prior=json.loads((p/rel).read_text())
  require(prior.get('release',{}).get('version_name')==version,'Historical receipt is not the original '+version+' release.')
  historical[version]={'snapshot':rel,'results':prior}
 provenance=['research/model-source/download-receipt.json','research/model-source/split-verification.json','research/model-source/model-verification.json']
 source_hashes={f.relative_to(p).as_posix():sha_file(f) for f in list((p/'android/src').rglob('*.java'))+web if distributable(f,p)}
 record={
  'release':receipt,'apk_source_assets_matched':len(web),'signing_certificate_sha256':SIGNING_SHA256,
  'native_device_install_and_launch':'UNVERIFIED: prior emulator operating system failed to finish startup; no new device test performed',
  'vehicle_test':'NOT PERFORMED; Highland sub-lens, rear-stop and marker mapping still require physical comparison',
  'current_release_receipts':results,
  'model_provenance_receipts':{f:json.loads((p/f).read_text()) for f in provenance},
  'prior_release_receipts':{'status':'Historical evidence retained separately; not represented as rerun against '+VERSION,'releases':historical},
  'source_sha256':source_hashes
 }
 atomic(p/'release-verification.json',(json.dumps(record,indent=2)+'\n').encode())
 files=set()
 for rel in ['web','android/src','android/res','signing','tools','research/upstream','research/evaluation-1.6','research/model-source','research/hardware-1.2.0']:
  files.update(f for f in (p/rel).rglob('*') if distributable(f,p))
 for rel in ['README.md','BUILD.md','VALIDATION.md','CHANGELOG.md','version.json','RELEASE_NOTES.md','release-verification.json','build.sh','android/AndroidManifest.xml']:
  files.add(p/rel)
 for pattern in ['tests/*.py','tests/*.java','tests/*.json','tests/*.cjs','tests/*.md','tests/*.txt','qa/audio-audit/*.java','qa/audio-audit/*.json','qa/audio-audit/*.md','qa/audio-audit/*.txt','qa/*.cjs','qa/*.js','qa/*.json','qa/*.md','qa/mobile/*.js','qa/mobile/*.cjs','qa/mobile/*.mjs','qa/mobile/*.json','qa/mobile/*.md','qa/mobile/*.png','qa/mobile/*.jpg','qa/mobile/*.webp','research/*.py','research/*.cjs','research/*.json','research/README.md']:
  files.update(p.glob(pattern))
 # Keep test programs and receipts, but omit generated audio/sequence fixtures and JVM classes.
 for rel in ['qa/hardware-1.2.0','qa/rig-audit','qa/music-1.3.0','qa/release-1.4.0','qa/release-1.5.0','qa/release-1.6.0']:
  files.update(f for f in (p/rel).rglob('*') if qa_distributable(f,p,p/rel))
 # Retain experimental model provenance and reproducible downloads, not unused weights or generated audio.
 files={f for f in files if not (any(part in {'separation-candidates','evaluation-1.6'} for part in f.relative_to(p).parts) and f.suffix.lower() in {'.onnx','.th','.pt','.pth','.f32','.wav','.mp3','.zip','.npz','.npy'})}
 require(all(distributable(f,p) for f in files),'A non-distributable source item was selected.')
 root=f'LightForge-{VERSION}/'
 content={root+'app/lightforge/'+f.relative_to(p).as_posix():f for f in sorted(files)}
 content[root+'START_HERE.md']=f'''# LightForge {VERSION} private source backup

The app project is in `app/lightforge/`. Open README.md for installation and use, BUILD.md to rebuild, and VALIDATION.md for test coverage and physical mapping limits.

This archive contains the complete Android and UI source, both bundled offline beat transformer models, selected stereo vocal-separation model, framewise singing/speech model, log-mel frontends and runtime, original neural conversion inputs, the licensed Highland GLB and geometry rebuild scripts, renderer source and pinned npm lock, fonts/licenses, private demo music, test code, Tesla hardware/command evidence, the music and movement planners, and result receipts. Current 1.6.0 separation, vocal detail, bass and transformer analysis, choreography, audio-layer audition, background compilation, recovery, preview, editing and integration verification is separated from historical 1.5.0 and earlier evidence. Generated test fixtures, discarded candidate model weights, compiled classes and npm dependencies are excluded; their source/generators are retained. It also contains the private signing key and password needed for compatible updates. Keep this entire archive private.

To build on Linux, change into app/lightforge, run `python3 tools/bootstrap_toolchain.py`, then `bash build.sh`. The pinned build toolchain is downloaded separately. Renderer JavaScript and the model are already supplied; optional graphics rebundling instructions are in BUILD.md.

The signed APK is a separate download. Install it over the existing app; do not uninstall first. Exported app show ZIPs are restorable project backups, including individual output settings and manual cues.
'''.encode()
 content[root+'qa/apk-signature-verification.txt']=p/'build/signature-verification.txt'
 content[root+'qa/apk-badging.txt']=p/'build/apk-badging.txt'
 status=workspace/'app/toolchain/EMULATOR_TEST_STATUS.md'
 if status.exists():content[root+'qa/ANDROID_RUNTIME_TEST_STATUS.md']=status
 source=out/f'LightForge-{VERSION}-Private-Source.zip'
 staged=stage_source_archive(source,root,content)
 try:
  apk_result=atomic_copy(apk,out/apk.name,receipt['sha256'])
  os.replace(staged['temporary_path'],source)
 finally:
  if staged['temporary_path'].exists():staged['temporary_path'].unlink()
 result={'apk':apk_result,'source':{'path':str(source),'bytes':staged['bytes'],'sha256':staged['sha256'],'entries':staged['entries']}}
 atomic(out/'LightForge-release-checksums.json',(json.dumps(result,indent=2)+'\n').encode())
 print(json.dumps(result,indent=2))

if __name__=='__main__':main()
