#!/usr/bin/env python3
"""Generate runtime version metadata from version.json; --check never changes files."""
from pathlib import Path
import json, sys
root=Path(__file__).resolve().parents[1]
v=json.loads((root/'version.json').read_text())
assert isinstance(v['code'],int) and v['code']>0 and len(v['name'].split('.'))==3 and all(p.isdigit() for p in v['name'].split('.'))
source='/* Generated by tools/sync_version.py from version.json. */\n(function(root){const value=Object.freeze('+json.dumps(v,separators=(',',':'))+');root.LightForgeVersion=value;if(typeof module!=="undefined"&&module.exports)module.exports=value;})(typeof window!=="undefined"?window:globalThis);\n'
target=root/'web/version.js'
if '--check' in sys.argv:
    if not target.exists() or target.read_text()!=source:raise SystemExit('Runtime version is stale. Run python3 tools/sync_version.py.')
    if json.loads((root/'package.json').read_text())['version']!=v['name']:raise SystemExit('package.json version does not match version.json.')
    lock=json.loads((root/'package-lock.json').read_text())
    if lock.get('version')!=v['name'] or lock.get('packages',{}).get('',{}).get('version')!=v['name']:raise SystemExit('package-lock.json version does not match version.json.')
else:target.write_text(source)
