/* Actual offline WebGL renderer regression with source-bound, fail-closed results. */
const fs=require('fs'),assert=require('assert'),http=require('http'),crypto=require('crypto'),path=require('path');
const root=path.resolve(__dirname,'..'),version=JSON.parse(fs.readFileSync(path.join(root,'version.json'))).name,outDir=process.env.LIGHTFORGE_PREVIEW_OUTPUT||path.join(root,'qa','release-'+version),port=Number(process.env.LIGHTFORGE_PREVIEW_PORT||8899),origin='http://127.0.0.1:'+port;
fs.mkdirSync(outDir,{recursive:true});
const receiptPath=path.join(outDir,'preview-verification.json');
const out={release:version,scope:'Desktop Chromium WebGL2 with SwiftShader software rasterization; no Android phone GPU or vehicle testing.',startedAt:new Date().toISOString(),status:'running',passed:false,checks:[],errors:[],externalRequests:[],quality:[],screenshots:[]};
// Invalidate any earlier success before loading browser dependencies or assets.
fs.writeFileSync(receiptPath,JSON.stringify(out,null,2));
const files=['web/version.js','web/preview/src/vehicle-preview.js','web/preview/src/highland-rig.js','web/preview/vehicle-preview.js','web/engine/show-engine.js','web/engine/light-planner.js','web/engine/movement-planner.js','web/engine/vehicle-profile.js','web/app.js','web/preview/models/highland.glb','tools/verify_preview_browser.cjs'];
const hashes=()=>Object.fromEntries(files.map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(root+'/'+p)).digest('hex')]));
const firstHashes=hashes();
const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>body{margin:0;background:#080d13;color:#e4efff;font:16px system-ui}main{width:390px;max-width:100%;padding-top:12px}h1,p{margin:12px;font-size:16px}canvas{display:block;width:100%;height:340px}button{padding:10px}#spacer{height:1800px}</style></head><body><main><h1>LightForge · Highland preview</h1><canvas id="carCanvas" tabindex="0"></canvas><p id="previewStatus"></p><button data-stage="studio">Studio</button><button data-stage="night">Night</button><p>2025 Model 3 · LR RWD · estimated motor travel</p></main><div id="spacer"></div><script src="version.js"></script><script src="engine/vehicle-profile.js"></script><script src="engine/light-planner.js"></script><script src="engine/movement-planner.js"></script><script src="engine/show-engine.js"></script><script src="preview/vehicle-preview.js"></script><script>window.preview=new VehiclePreview(document.querySelector('canvas'));window.qualityEvents=[];preview.canvas.addEventListener('previewperformance',e=>qualityEvents.push(e.detail));const frames=new Uint8Array(4000*200);function set(ch,start,end,v){for(let f=Math.floor(start*50);f<Math.floor(end*50);f++)frames[f*200+ch-1]=v;}set(3,1,3,204);set(5,0,3,255);set(25,0,3,255);set(28,0,3,255);set(30,0,3,255);set(37,0,.5,63);set(41,0,.5,63);set(35,0,.5,191);set(46,0,2,63);set(46,2,5,127);for(let f=0;f<4000;f++){frames[f*200+175]=64;frames[f*200+176]=128;frames[f*200+177]=255;}window.show={frames,frameCount:4000,stepMs:20,channels:200,channelCount:200,duration:80,sections:[{start:0,end:80,label:'Preview test'}]};window.renderAt=t=>preview.render(ShowEngine.stateAt(show,t),t);</script></body></html>`;
async function settle(page){await page.waitForFunction(()=>preview.loaded&&!preview._raf&&!preview.tween&&preview.renderCount>0,{},{timeout:30000});}
function assetServer(){
 const webRoot=path.join(root,'web');
 const mime={'.js':'application/javascript','.glb':'model/gltf-binary','.gz':'application/gzip','.json':'application/json','.png':'image/png','.jpg':'image/jpeg'};
 return http.createServer((request,response)=>{
  let name;try{name=path.resolve(webRoot,'.'+decodeURIComponent(new URL(request.url,origin).pathname));}catch{response.writeHead(400);response.end();return;}
  if(!name.startsWith(webRoot+path.sep)){response.writeHead(403);response.end();return;}
  const stream=fs.createReadStream(name);stream.once('open',()=>{response.setHeader('Content-Type',mime[path.extname(name)]||'application/octet-stream');stream.pipe(response);});stream.once('error',()=>{if(!response.headersSent)response.writeHead(404);response.end();});
 });
}
(async()=>{const server=assetServer();let browser;try{
 const {chromium}=require('playwright');
 await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',resolve);});
 browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:393,height:852},deviceScaleFactor:2,reducedMotion:'reduce'});page.on('pageerror',e=>out.errors.push(e.message));await page.route('**/*',r=>{const u=new URL(r.request().url());if(u.origin!==origin){out.externalRequests.push(u.href);return r.abort();}if(u.pathname==='/preview-test')return r.fulfill({contentType:'text/html',body:html});return r.continue();});await page.goto(origin+'/preview-test');assert(await page.evaluate(()=>preview.ready));await settle(page);
 out.graphics=await page.evaluate(()=>{const p=preview,gl=p.renderer.getContext();let meshes=0,triangles=0;p.rig.root.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;}});return {webgl2:gl instanceof WebGL2RenderingContext,renderer:gl.getParameter(gl.RENDERER),meshes,triangles};});assert(out.graphics.webgl2);assert(out.graphics.triangles>170000);out.checks.push('Loads unchanged detailed Highland geometry in actual WebGL2.');
 // Simulated media-clock delay verifies the actual bundled GPU submission path.
 const presentation=await page.evaluate(async()=>{window.mediaTime=0;preview.setStateSource(()=>({data:ShowEngine.stateAt(show,mediaTime),time:mediaTime,clock:'test-media-time'}));renderAt(0);mediaTime=1.5;await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);const result={snapshot:preview.getSnapshot(),presentation:preview.getPerformance().presentation};preview.setStateSource(null);return result;});
 assert.equal(presentation.presentation.frame,75);assert.equal(presentation.presentation.time,1.5);assert.equal(presentation.snapshot.frame,75);out.clockSubmission=presentation.presentation;out.checks.push('Bundled renderer reads the authoritative clock at GPU submission and replaces a deliberately stale queued frame.');
 await page.evaluate(()=>renderAt(1.5));await settle(page);
 const physicalSpill=await page.evaluate(()=>{const p=preview,world=light=>light.getWorldPosition(light.position.clone()).toArray();p.getSnapshot();const before={tail:world(p.tailSpill[0]),reverse:world(p.reverseSpill[0])};renderAt(15);p.getSnapshot();const after={tail:world(p.tailSpill[0]),reverse:world(p.reverseSpill[0])};const result={before,after,tailAttached:p.tailSpill.every(light=>light.parent===p.rig.parts.trunk&&light.target.parent===p.rig.parts.trunk),reverseBodyFixed:p.reverseSpill.every(light=>light.parent===p.scene),headlights:p.headlights.map(light=>light.intensity)};renderAt(1.5);p.getSnapshot();return result;});
 assert(physicalSpill.tailAttached&&physicalSpill.reverseBodyFixed);assert.deepStrictEqual(physicalSpill.before.reverse,physicalSpill.after.reverse);assert.notDeepStrictEqual(physicalSpill.before.tail,physicalSpill.after.tail);out.physicalSpill=physicalSpill;out.checks.push('Tail illumination originates at lid-mounted optics and moves with the trunk while fascia reverse illumination stays body-fixed.');
 const expected=await page.evaluate(()=>preview.getSnapshot());assert(Math.abs(expected.lamps.find(x=>x.id===3).value-.5)<.011);
 for(const quality of ['high','balanced','battery']){
  await page.evaluate(q=>preview.setQuality(q),quality);await settle(page);const current=await page.evaluate(()=>({snapshot:preview.getSnapshot(),performance:preview.getPerformance(),emitter:preview.rig.lamps.find(x=>x.id===3).object.material.emissiveIntensity,frame:preview.last[0].frame,shadowAuto:preview.renderer.shadowMap.autoUpdate}));assert.deepStrictEqual(current.snapshot,expected);assert.equal(current.emitter,3.5);assert(current.performance.bloomEnabled);assert.equal(current.performance.effectiveQuality,quality);assert.equal(current.shadowAuto,false);out.quality.push(current.performance);
  const path=`${outDir}/preview-${quality}.png`;await page.locator('main').screenshot({path});out.screenshots.push(path);
 }
 assert(out.quality[0].pixelRatio>out.quality[1].pixelRatio&&out.quality[1].pixelRatio>out.quality[2].pixelRatio);assert.deepStrictEqual(out.quality.map(x=>x.shadowSize),[1024,512,256]);out.checks.push('All manual qualities change raster/shadow resolution while preserving exact frames, fades, RGB, closure states, every emitter and estimated-mapping flags.');
 assert(await page.evaluate(()=>{try{preview.setQuality('invalid');return false;}catch(e){return e instanceof RangeError;}}));assert.equal(await page.evaluate(()=>localStorage.getItem('lightforge-preview-quality')),'battery');out.checks.push('Quality preference persists and invalid modes fail explicitly.');
 const frozen=await page.evaluate(()=>preview.renderCount);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>preview.renderCount),frozen);out.checks.push('Paused, settled preview does not continually redraw.');
 // Projection data is lazy. During playback update neither scans provenance nor allocates snapshots until asked.
 const lazy=await page.evaluate(()=>{let calls=0;const original=preview.updateSnapshot;preview.updateSnapshot=function(...a){calls++;return original.apply(this,a);};for(let i=0;i<40;i++)renderAt(1+i*.02);const before=calls;const snap=preview.getSnapshot(),after=calls;preview.updateSnapshot=original;return {before,after,time:snap.time,frame:snap.frame};});assert.equal(lazy.before,0);assert.equal(lazy.after,1);assert.equal(lazy.frame,89);out.checks.push('Forty sequence updates perform no snapshot projections until requested; the requested snapshot uses the latest exported frame.');
 await settle(page);await page.evaluate(()=>window.scrollTo(0,1200));await page.waitForFunction(()=>!preview.getPerformance().visible);const offscreen=await page.evaluate(()=>preview.renderCount);await page.evaluate(()=>{for(let i=0;i<20;i++)renderAt(2+i*.02);});await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>preview.renderCount),offscreen);await page.evaluate(()=>window.scrollTo(0,0));await page.waitForFunction(()=>preview.renderCount>0&&preview.getPerformance().visible);await settle(page);assert.equal(await page.evaluate(()=>preview.getSnapshot().frame),119);out.checks.push('IntersectionObserver stops all offscreen drawing and resumes at the newest sequence frame.');
 // Actual display:none removes size, also guarded without relying on viewport intersection.
 await page.evaluate(()=>preview.canvas.style.display='none');await page.waitForFunction(()=>!preview.getPerformance().visible);const hidden=await page.evaluate(()=>preview.renderCount);await page.evaluate(()=>renderAt(3));await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>preview.renderCount),hidden);await page.evaluate(()=>preview.canvas.style.display='block');await page.waitForFunction(()=>preview.getPerformance().visible);await settle(page);out.checks.push('Zero-size/hidden canvases do not submit graphics work.');
 // Clock does not change when quality changes or when draw intervals are irregular.
 const rewind=await page.evaluate(()=>{renderAt(1.5);const a=preview.getSnapshot();renderAt(2.7);const b=preview.getSnapshot();preview.setQuality('high');renderAt(1.5);return {a,b,c:preview.getSnapshot()};});assert.deepStrictEqual(rewind.a,rewind.c);assert.notDeepStrictEqual(rewind.a.closures,rewind.b.closures);out.checks.push('Backward seeking restores deterministic geometry, fade/RGB values and frame across quality changes.');
 // Sustained policy test feeds named synthetic timing samples; this is not a device performance benchmark.
 out.adaptationPolicy=await page.evaluate(()=>{const p=preview;p.setQuality('auto');p.applyQuality('high','Policy fixture');p._warmupFrames=0;p._sampleCount=0;p._lastRenderAt=10000;p._lastQualityChange=0;for(let i=1;i<=30;i++)p.recordPerformance(10000+i*90,60);const slow=p.getPerformance();p.applyQuality('balanced','Policy recovery fixture');p._warmupFrames=0;p._sampleCount=0;p._lastRenderAt=30000;p._lastQualityChange=0;for(let i=1;i<=190;i++)p.recordPerformance(30000+i*16,4);const fast=p.getPerformance();p.setQuality('high');p._warmupFrames=0;p._sampleCount=0;p._lastRenderAt=50000;p._lastQualityChange=0;for(let i=1;i<=40;i++)p.recordPerformance(50000+i*100,75);return {slow,fast,manual:p.getPerformance(),synthetic:true};});assert.equal(out.adaptationPolicy.slow.effectiveQuality,'balanced');assert.equal(out.adaptationPolicy.fast.effectiveQuality,'high');assert.equal(out.adaptationPolicy.manual.effectiveQuality,'high');assert(out.adaptationPolicy.slow.bloomEnabled);out.checks.push('Synthetic sustained timing samples verify adaptive downgrade, slower recovery hysteresis, and no override of explicit quality.');
 await page.evaluate(()=>{preview.setQuality('battery');preview._warmupFrames=0;preview._sampleCount=0;preview._lastRenderAt=0;});await settle(page);
 out.measuredVisibleRendering=await page.evaluate(()=>new Promise(resolve=>{let i=0;const intervals=[];let previous=performance.now();function run(now){intervals.push(now-previous);previous=now;renderAt(1.5+(i++)*.02);if(i<18)requestAnimationFrame(run);else requestAnimationFrame(()=>resolve({...preview.getPerformance(),intervals}));}requestAnimationFrame(run);}));assert(out.measuredVisibleRendering.samples>0);out.checks.push('Reports observed continuous rendering intervals and CPU submission time with explicit software-renderer scope.');
 await settle(page);await page.evaluate(()=>{preview.setQuality('high');preview.setView('rear');});await settle(page);await page.locator('main').screenshot({path:outDir+'/preview-rear.png'});out.screenshots.push(outDir+'/preview-rear.png');
 const hue=await page.evaluate(()=>{preview.composer.render();const gl=preview.renderer.getContext(),pixels=new Uint8Array(gl.drawingBufferWidth*gl.drawingBufferHeight*4);gl.readPixels(0,0,gl.drawingBufferWidth,gl.drawingBufferHeight,gl.RGBA,gl.UNSIGNED_BYTE,pixels);let red=0,amber=0;for(let i=0;i<pixels.length;i+=4){const r=pixels[i],g=pixels[i+1],b=pixels[i+2];if(r>100&&r>g*1.8&&r>b*1.8)red++;if(r>100&&g>r*.4&&g<r*.8&&b<r*.3)amber++;}return {redPixels:red,amberPixels:amber};});assert(hue.redPixels>50&&hue.redPixels>hue.amberPixels,'Stop/tail fixture must remain visibly red, not tone-mapped into amber');out.stopLampHue=hue;out.checks.push('Actual output framebuffer preserves red stop/tail optics instead of desaturating them into amber.');await page.evaluate(()=>preview.setView('cabin'));await settle(page);assert.equal(await page.evaluate(()=>preview.getSnapshot().view),'cabin');await page.locator('main').screenshot({path:outDir+'/preview-cabin.png'});out.screenshots.push(outDir+'/preview-cabin.png');out.checks.push('Rear and cabin cutaway cameras remain functional after adaptive quality changes.');
 await page.evaluate(()=>preview.setQuality('battery'));await settle(page);
 const hasExtension=await page.evaluate(()=>{window.loss=preview.renderer.getContext().getExtension('WEBGL_lose_context');if(!loss)return false;loss.loseContext();return true;});assert(hasExtension);await page.waitForFunction(()=>preview.lost);const stopped=await page.evaluate(()=>preview.renderCount);await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>preview.renderCount),stopped);await page.evaluate(()=>loss.restoreContext());await page.waitForFunction(()=>!preview.lost&&preview.canvas.dataset.rendererState==='ready');await page.waitForFunction(n=>preview.renderCount>n,stopped);assert.equal(await page.evaluate(()=>preview.effectiveQuality),'battery');assert(await page.evaluate(()=>preview.bloom.enabled));out.checks.push('Actual graphics-context loss pauses and restores current quality, bloom and drawing.');
 await settle(page);const beforeDispose=await page.evaluate(()=>{const n=preview.renderCount;preview.dispose();preview.requestDraw();return n;});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>preview.renderCount),beforeDispose);out.checks.push('Disposal disconnects observers and stops scheduling further frames.');
 assert.deepStrictEqual(out.errors,[]);assert.deepStrictEqual(out.externalRequests,[]);out.sourceHashes=hashes();assert.deepStrictEqual(out.sourceHashes,firstHashes,'Preview dependencies changed during verification; rerun final source.');out.passed=true;out.status='passed';out.completedAt=new Date().toISOString();fs.writeFileSync(receiptPath,JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
 }finally{await browser?.close();server.closeAllConnections?.();await new Promise(resolve=>server.close(resolve));}})().catch(e=>{out.passed=false;out.status='failed';out.completedAt=new Date().toISOString();out.failure=String(e.stack||e);fs.writeFileSync(receiptPath,JSON.stringify(out,null,2));console.error(e);process.exitCode=1;});
