/* Private worker: bounded-memory WAV reading -> features -> trained CRNN -> rhythm. */
'use strict';
importScripts('wav-reader.js','dsp.js','vendor/ort.wasm.min.js');
const report=(progress,stage,detail='')=>postMessage({type:'progress',value:{progress,stage,detail}});
self.onmessage=async e=>{let session;try{
 const {audioUrl,options={}}=e.data;report(0.01,'Opening music','Reading the selected file locally');const reader=new LightForgeWavReader(options.analysisUrl||audioUrl);await reader.open();
 const config=await (await fetch('models/features.json')).json();const n=Math.ceil(reader.duration*50);const data={duration:reader.duration,beat:new Float32Array(n),down:new Float32Array(n),rms:new Float32Array(n),bass:new Float32Array(n),mid:new Float32Array(n),high:new Float32Array(n),colour:new Float32Array(n*3),fineRms:new Float32Array(n*4)};
 report(0.035,'Loading music AI','BeatNet CRNN • on-device • no account needed');ort.env.wasm.wasmPaths=new URL('vendor/',self.location.href).href;ort.env.wasm.numThreads=1;ort.env.wasm.proxy=false;
 session=await ort.InferenceSession.create(new URL('models/beatnet-v1.onnx',self.location.href).href,{executionProviders:['wasm'],graphOptimizationLevel:'all',enableCpuMemArena:true});
 const extractor=new LightForgeDSP.FeatureExtractor(config);let hidden=new Float32Array(300),cell=new Float32Array(300);const chunk=500;const started=performance.now();
 for(let first=0;first<n;first+=chunk){const frames=Math.min(chunk,n-first),sampleStart=first*441-705,samples=await reader.mono22050(sampleStart,(frames-1)*441+1411,config);const f=extractor.extract(samples,0,frames);const out=await session.run({features:new ort.Tensor('float32',f.features,[1,frames,272]),h:new ort.Tensor('float32',hidden,[2,1,150]),c:new ort.Tensor('float32',cell,[2,1,150])});hidden=new Float32Array(out.hn.data);cell=new Float32Array(out.cn.data);const p=out.probabilities.data;for(let i=0;i<frames;i++){data.beat[first+i]=p[i*3];data.down[first+i]=p[i*3+1];}for(const name of ['rms','bass','mid','high'])data[name].set(f[name],first);data.colour.set(f.colour,first*3);data.fineRms.set(f.fineRms,first*4);for(const value of Object.values(out))if(value.dispose)value.dispose();report(0.055+0.86*(first+frames)/n,'Finding beats and musical detail',`${Math.min(reader.duration,(first+frames)*0.02).toFixed(0)} / ${reader.duration.toFixed(0)} seconds analyzed`);}
 report(0.94,'Shaping musical phrases','Following beat accents, energy changes and instrument attacks');const result=LightForgeDSP.summarize(data,options);result.engine={name:'BeatNet CRNN',neural:true,detail:'Bundled pretrained BeatNet model 1 with ONNX Runtime WebAssembly. Neural beat/downbeat activations, adaptive local-tempo decoding, 5 ms PCM attack alignment, silence-aware bar/phrase landmarks and impact analysis. All audio stays on this device.',model:'BeatNet model_1_weights',runtime:'ONNX Runtime Web 1.20.1',analysisSeconds:Math.round((performance.now()-started)/100)/10};result.recommendedAudio={sampleRate:44100,channels:2,format:'PCM16 WAV'};report(1,'Music understood',`${result.bpm?result.bpm+' BPM':'No pulse detected'} • ${result.sections.length} sections`);await session.release();session=null;postMessage({type:'result',value:result});
 }catch(error){if(session)try{await session.release();}catch(_){}postMessage({type:'error',message:error.message||String(error)});}};
