/* Generated by tools/sync_version.py from version.json. */
(function(root){const value=Object.freeze({"name":"2.3.2","code":20302});root.LightForgeVersion=value;if(typeof module!=="undefined"&&module.exports)module.exports=value;})(typeof window!=="undefined"?window:globalThis);
